### ISSUE TITLE
2.x: Re-Import Metadata from external Sources

### ISSUE THREAD

**Issue by M3ssman** [kitodo/kitodo-production#2800]
Hello,

is it possible to have a process that has been already created to re-import Metadata from PICA or other external Sources again, say at structuring stage?

Use-Case: at Pagination or Structuring Stage we often get new insights about an Issue, like missing pages, or it is a special Edition, or it turns out to be part of multi-volume or series or the catalogue-Stage just did some mistakes ... Things we do not know before but must be taken into account. In this case the Digitalisat is already listed at external Catalogues.

To do so right now it is only possible to create a brand new process or to update the data inside Kitodo and at exernal catalogues by using some external like `WinIBW`, but afterwards we have 2 different places to watch out for, which is error prone, too.

Maybe I missed something?

Greetings!

**Comment by henning-gerhardt** [comment]
In Kitodo.Production 2.x is it not possible to re-import a whole set of meta data for a existing process. If you have this scenario that your process or document / media type should be a multi volume work instead of a monograph then you must do the hard way:
- save the images from the process in a temporary folder
- delete the process
- re-create the process
- re-import the saved images

So far as I know if you use the import of meta data inside the meta data editor through "add docstructs from opac" on the structure data page and your used rule set is defined in a proper way to allow that than you may can "update" the meta data of the structure. But we (SLUB Dresden) did not use this feature as your catalogue data and our rule set are not defined to allow that.

**Comment by M3ssman** [comment]
@henning-gerhardt 
Thank for your advices! We'll give the import inside the meta data editor a try.

So as by now it is not possible in Kitodo 3 ?

**Comment by M3ssman** [comment]
@henning-gerhardt 

We've followed your suggestion using the "add structure from opac" -> "only metadata". It turned out to do strange things, like duplication of existing metadata or swallowing it somewhere. Therefore we could not handle it right away to our structure-operators.

By now I've changed the Metadaten#AddMetadaFromOpacPpn from 2.x-Branch to behave as desired, which works quite well, besides MetadataGroup for Person, which is still missing. As a side note I stumbled upon an (IMHO) unexpected behaviour regarding changes of existing metadata [https://github.com/kitodo/kitodo-ugh/pull/91](https://github.com/kitodo/kitodo-ugh/pull/91)
