### ISSUE TITLE
3.0: Folders, images and metadata editor

### ISSUE THREAD

**Issue by mnscholz** [kitodo/kitodo-production#3176]
Hi,

I got stuck when testing Kitodo's metadata editor:
I try to figure out how I have to configure a project, its folders and the workflow to get the a working metadata editor. I managed that the editor shows the images by defining an "images" folder for tiffs. When I put .tif files in there, they are detected and displayed in the editor. However, no thumbs are being displayed. I guess I have to define a separate folder (and possibly a workflow step?) with generation of derivatives. How do I do that correctly?

Is there any documentation, how-to or example config for that?

Thanks!

**Comment by matthias-ronge** [comment]
If you started with the standard database, everything should already be set correctly. It should look like this:

![Image: project configuration](https://user-images.githubusercontent.com/3040657/74416496-81772300-4e45-11ea-86ae-aa56aaabc2ac.png)
Thumbs folder settings:

![Image: Thumbs folder configuration](https://user-images.githubusercontent.com/3040657/74416504-84721380-4e45-11ea-86c5-15e8e95a8ed5.png)

The images can come from at least four ways:

1. You already have thumbnail versions of your images (generated by another program) and copy them into the thumbs folder manually. (In this case: generate images should be "off" in the subfolder settings of thumbs).
1. You set up your own workflow step in the workflow editor. Select "Generate Images" and "Automatic Task" and the step will execute on itself. ![Image: Generate images workflow step](https://user-images.githubusercontent.com/3040657/74417321-c9e31080-4e46-11ea-9d69-e61c95cf15ef.png)
1. You set up a workflow step for manual creation in the workflow editor. Select "Generate images", but without "automatic task". For example, in the QC step, if the QC agreed, it creates the images. For this purpose, additional buttons appear in the task undertaken. The QC operator can then start generation manually.
1. On the "Processes" dialog page, select "possible actions", "execute KitodoScript", "generateImages". Example: `action:generateImages folders:all images:all`

In order to generate the images, the originals must be stored in the folder that is set in "use as source to generate contents". ImageMagick must be installed on the computer (does not come bundled with installation). On Windows you have to define the ImageMagick path in `kitodo_config.properties` (on Linux this usually works).

**Comment by mnscholz** [comment]
Thank you for the detailed explanation! I got it working!
I encountered two gotchas that weren't obvious to me and maybe are bugs or features:
1. The filenames of the images must consist of digits only. I had tested it with images containing alphanum characters, which prevents derivatives from being created and (if manually created) from being displayed in the metadata editor.
2. When a manual task for image generation is defined, all task of the process are shown the options for generating images, even if they don't have the property checked. If image generation is triggered in the wrong task, however, the generation fails without error notice -- in contrary a green status message is displayed as if everything is ok. In the task list, a task is shown with state terminated normally but low progress.

![A task with no image generation rights](https://user-images.githubusercontent.com/1378632/74518011-72f73d00-4f13-11ea-921b-53bf1412378e.jpg)
![For same task, option to generate images is shown](https://user-images.githubusercontent.com/1378632/74518018-74286a00-4f13-11ea-9acb-967e1e9e3dc0.jpg)
![The task fails silently](https://user-images.githubusercontent.com/1378632/74518015-738fd380-4f13-11ea-9ed6-07fdcf3d3292.jpg)

**Comment by matthias-ronge** [comment]
Progress is percent, if this isn’t 100 then something gone wrong here. Related #3172

**Comment by mnscholz** [comment]
Yes, I guessed it should be percent. However, the 29% are weird: my test scenario contains 5 tiffs. Why does it then stop at 29% when no file is being generated. I would have expected something like 20% or 0%...

There remains the problem, that the system doesn't seem to produce any error message or the like that describes what went wrong. From the "Status" field and the green status message you get the impression that everything is fine.

**Comment by Kathrin-Huber** [comment]
Most of the problems here are fixed. Remaining ones are in separate issues.

**Comment by solth** [comment]
>     I had tested it with images containing alphanum characters, which prevents derivatives...from being displayed in the metadata editor.

This has been fixed with #3459
