### ISSUE TITLE
Migration of metadata possible for all projects

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3191]
The migration functions for metadata show all projects, even if they are not assigned to the user. Is this okay for migration, or should only those projects be possible that are allowed for the operator?

**Comment by Kathrin-Huber** [comment]
it's ok, because the migration is usually done by a single admin. Furthermore, the migration is based on database, because it should be done before indexing. If user should be assigned to projects (which is not possible in the frontend, because index is not working) it needs to be done in the database.
We decided, that the administrator which is doing the migration should handle all data at once.
