### ISSUE TITLE
Hide "Conditions" tab for non-parallel tasks

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3362]
Workflow editor: The "Conditions" tab is irrelevant and irritated for non-parallel tasks. In this case, it should not be displayed.

**Comment by solth** [comment]
I would suggest to deactivate the tab instead of hiding it for non-parallel tasks. That would be more in line with other UI elements that are normally available but cannot be used in specific situations. If we deactivate the tab instead of hiding it, we could also add a tooltip to the deactivated tab, explaining why it is not available for the selcted task in the workflow.

**Comment by Erikmitk** [comment]
I’m going to look into it. I’m not sure if I have a mechanism at hand to distinguish parallel and non-parallel tasks.

**Comment by solth** [comment]
Is it possible to just check the `checked` state of the last checkbox of the first tab `Properties` using Javascript?

<img width="280" alt="concurrent_task" src="https://user-images.githubusercontent.com/19183925/78772021-64685780-7991-11ea-9798-9f7542f68460.png">

**Comment by Erikmitk** [comment]
Yes, that should work. Only of this is checked the tab gets activated.

**Comment by Erikmitk** [comment]
But wait… why are non-parallel tasks not allowed to have a condition attached? What's the rationale behind that? If it's just a series of steps you could have a condition that makes a task optional. What am I missing?

**Comment by solth** [comment]
@Erikmitk If you put it this way, I think you are actually right. Even in a linear workflow it should be possible to skip individual tasks if corresponding condtions are not met.

**Comment by matthias-ronge** [comment]
Will the workflow engine also support this? What happens then? It skips the step and the next one is set to open? @frank-ulrich-weber, what do you think?

**Comment by Erikmitk** [comment]
> Will the workflow engine also support this? What happens then? It skips the step and the next one is set to open? @frank-ulrich-weber, what do you think?

That's what it's doing right now if I get that right. Check out the place were the condition is evaluated:
https://github.com/kitodo/kitodo-production/blob/da20bbd0d27ecbcd0f550ef65bef0bcb80286ad7/Kitodo/src/main/java/org/kitodo/production/services/workflow/WorkflowControllerService.java#L598

If the condition is true the task will be opened, otherwise the next one is activated. This goes on until we find one we can work with.

**Comment by Kathrin-Huber** [comment]
You are right! A condition can be set to every task!
So this Issue is not relevant anymore.
