### ISSUE TITLE
[Solved] How to assign all media to the root element

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3380]
A workpiece was created, it only has the root element and pictures. No finer structure should be created (like one scientific article which has only five sheets). The media should be assigned to the root element. How is this done?

![Screenshot 1](https://user-images.githubusercontent.com/3040657/78369813-108ef480-75c6-11ea-9ab5-8369075dd01a.png)

There is no way to assign unstructured media to the root element (here: monograph) in the gallery. When we used the _assign pages_ dialog, we got this:

![Screenshot 2](https://user-images.githubusercontent.com/3040657/78370003-551a9000-75c6-11ea-9af0-8b20f9fb051f.png)

**Comment by solth** [comment]
Media that is shown in the `Unstructured media` area is effectively assigned to the root element. The terminology was chosen because all media that isn't assigned to sub structures is assigned to the root element automatically (so technically `Unstructured media` acts like an alias for `root element` in the structured view of the gallery). 

You can verify this by saving the process in the metadata editor and inspecting the meta.xml file, it should contain the correspoding `smLink` elements between the individual pages and the div of the root element.
