### ISSUE TITLE
Missing truncation in the filter of the task list

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3402]
### Problem
In the task list, processes can be found only, when the complete process title is entered. For example. 
- SrKMai_1438157967_2
- FnfSpunP_1688451722

Practically, users search often only the identifier, especially, when several processes of a newspaper should be shown. For example: 
- 1438157967
- 1688451722

The TSL_ATS and the suffix in the process title is often not known by the users and a search not possible. 

### Solution
In Kitodo.Production 2.x process titles were truncated left and right sided. That should be possible in Kitodo.Production 3.x, too.

**Comment by matthias-ronge** [comment]
Truncating the search query left and right is counterproductive in how the search engine works. Basically, it works, but it first becomes a large OR of all indexed strings that contain the substring, which is then searched for. The solution to this is to customize the tokenization. That is, for `SrKMai_1438157967_2`, not only `srkmai_1438157967_2` is indexed, but also `srkmai`, `srkmai_1438157967`, `1438157967`, `1438157967_2` and `2`, so that query e.g. after `1438157967` is possible. Adaptation of this is the task of the search engine preprocessing.

**Comment by andre-hohmann** [comment]
I am ok with that, too! 
For me, it is only important that the user finds the processes easily.
