### ISSUE TITLE
Order of structure elements by adding a new docstruct 

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3413]
### Problem
It is presumed that the list of structure elements which is shown by adding a new structure element in the metadata editor is sorted according the _internal names_ of the strucure elements. 
For the lucky users, who are not familiar with the ruleset, that order is very uncomfortable. 

![sortingstructureelements01](https://user-images.githubusercontent.com/14835770/78793980-6ba05d00-79b3-11ea-96b7-14a2e14a9e4f.jpg)

### solution
The structure elements should be sorted according to their "official" displayed names. 

There has been a similar problem with the sort order of the metadata elements.

**Comment by matthias-ronge** [comment]
The order from the ruleset is the order of the `<permit>` rules; If `unspecified="unrestricted"`, followed by the divisions not mentioned in a `<permit>` rule in alphabetical order according to the display language. This is for if you don't use `unspecified="forbidden"`, you can move frequently used elements to the beginning of the (probably lengthy) list.

**Goal:** The sorting should take place if the ruleset setting “order as in the rule set, otherwise alphabetical” is _off_. If it is _on_, the order of the ruleset should be used.
