### ISSUE TITLE
Result of statistical analysis is shown after change of result page  

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3430]
### Problem
The result of the statistical analysis of a specific amount of processes is shown at the bottom of the process list even if the result list is changed, or the process list is selected completely new. 

### Solution
The result of the statistical analysis should be deleted as soon as changes in the process list or other actions (as moving to task view an then back to process list) are conducted.

**Comment by solth** [comment]
Instead of displaying the statistical figures _below_ the process list, I would suggest to display them in a separate dialog window _overlaying_ the list. Not only would this look much better, but it would prevent the user from changing the selection of displayed processes until the pop-up dialog is closed. Thus the displayed processes and statistics would be kept synchronized.

Furthermore, it would remove the need to scroll down to see the statistics (a few times I didn't even notice the statistics had been generated because they were out of the view)
