### ISSUE TITLE
Metadata-file is not exported in the export folder of the process

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3431]
### Problem
The metadata file is not exported into the export folder of the process, into which the images are imported. The metadata file is exported in the general export folder, as for example:

Export folder
    Process folder 1
        Images
    Process folder 2
        Images
    Process folder 3
        Images
    …
    meta_process_1.xml
    meta_process_2.xml
    meta_process_3.xml
    …

### Solution
The metadata file of a process should be exported into the export folder of the folder, as for example:

Export folder
    Process folder 1
        Images
        meta_process_1.xml
    Process folder 2
        Images
        meta_process_2.xml
    Process folder 3
        Images
        meta_process_3.xml
    …

**Comment by matthias-ronge** [comment]
In version 2, two settings determined how export was written.

First, there was a check box in the project configuration named “Create process folder”. It caused a subfolder to be created in the export folder for the process and to be exported there.

Create process folder "off":
```
📁 hotfolder
  🗎  LoremIpsum_1234567.xml
  📁 LoremIpsum_1234567_tif/
    🖼️ 00000001.tif
    🖼️ 00000002.tif
```

Create process folder "on":
```
📁 hotfolder
  📁 LoremIpsum_1234567
    🗎  LoremIpsum_1234567.xml
    📁 LoremIpsum_1234567_tif/
      🖼️ 00000001.tif
      🖼️ 00000002.tif
```

Second, there was a check box “Bulk downloads” in the user settings. It caused a subfolder to be created in the export folder, or home directory, for the project (and in it the folder for the process, if desired). This option did never work properly if the project name contained spaces! So, in total, version 2 could export to eight different locations.

As long as, in 2.x, only the `_tif` folder has been exported and it contains the process name as part of it, this does not cause data to be overwritten. With version 3 it is different, e.g. for `jpgs` folders, that would overwrite each other. That's why folder is always on. The functionality [has been removed](https://github.com/kitodo/kitodo-production/pull/3345).

At the same time, for example scripts from 2.x for export processing, expect layout in this way, otherwise the recognition will not work. It seems like it was thought too short to remove the functionality.

My suggestion is to make configurable for each folder, in which target folder it should be exported. The absolute path for the hot folder must be specified, otherwise it is relative to the user directory. The same must be possible for the METS file to be written. A variable `(projecttitle)` should be provided.

**Comment by matthias-ronge** [comment]
I added the <kbd>question</kbd> badge because it requires agreement on how to implement it.

**Comment by andre-hohmann** [comment]
@matthias-ronge: 
From whom is agreement required? Is it a technical question?

**Comment by matthias-ronge** [comment]
From you all. So far, this is just a suggestion from me.

**Comment by Kathrin-Huber** [comment]
@matthias-ronge  Please implement, that the meta.xml is exported to the project folder per default. (as requested in the issue description)
