### ISSUE TITLE
Warning "Systemwartung" is shown, when a new user signs in

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3433]
### Problem
When a new user signs in, the following warning is shown: 

![systemwarnung](https://user-images.githubusercontent.com/14835770/79189066-1932c680-7e21-11ea-88bc-1517f0b506ef.jpg)

### Solution
New users schould be able to sign in.

**Comment by solth** [comment]
This message is displayed on login if the index is currently being rebuild and the user trying to log in has no rights to manipulate the index. 
In that case the user is prevented from entering the  system because it is not ready to use (because it would produce a lot of errors when working with an outdated index) and the user has no means to fix the problem himself.
