### ISSUE TITLE
Definition of workpiece properties and template properties

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3482]
### Problem
It is not clear which properties are saved in workpiece properties and which one in template properties. 
It seems, as if now all properties are saved in workpiece properties. 

### Solution
Information and description about the configuration of the properties.

**Comment by matthias-ronge** [comment]
Properties are no longer supported in 3.x. They have been replaced by the availability of the METS sections `techMD` (properties), `sourceMD` (template properties) and `dmdSec` (workpiece properties). `processProperties.xml` configuration was integrated in the ruleset. The configuration per accepted task is replaced by the acquisition stage. Technically, properties are still included because issue #3335 has not yet been implemented. Acquisition stages not yet available because issue #3155 has not yet been implemented. At the moment, properties can also not be edited in the accepted task because issue #3156 has not yet been implemented.

**Comment by andre-hohmann** [comment]
See #4317
