### ISSUE TITLE
Combination of "process data" and "process metadata" for creation of a new process

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3529]
It could be helpful, if the data fields of "process data" and "process metadata" are combined, when a process is created. As both options have pros and cons, that should be discussed in the community. 

The issue was created due to the following reasons: 
- Even if it is only one click more, to change the tab: The more processes are created, the more uncomfortable it feels. 
- The more processes are created, the more often mandatory metadata is forgotten and it is necessary to open the tabs "process data" and "process metadata" to correct the data, if theprocess title has to be generated again. 

![vorgangsdaten01](https://user-images.githubusercontent.com/14835770/80195752-9c6fcb80-861c-11ea-9aee-deaf25b15568.jpg)

![vorgangsdaten02](https://user-images.githubusercontent.com/14835770/80195760-a0035280-861c-11ea-91f6-ab329831c97a.jpg)

**Comment by matthias-ronge** [comment]
I am absolutely in favor of combining the two tabs. Another problem is: When validation errors occur during the save process, some of them are not visible because they are currently on the other tab.

With the other fields on the first tab, we can think about what needs to be there at all. In my opinion, the fields for the Tiff headers could be contained on a separate tab (if at all - does anyone actually use it?), the ruleset should be defined by the production template and not be changeable at all. Whether the estimated page numbers are ever needed for anything is also questionable, as is what the "Show in selection list" button does. This “selection list” doesn't even exist in version 3, does it?
