### ISSUE TITLE
Several processes for the year-level of newspapers

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3545]
When processes of one year for newspapers are created successively, a "year-process" is created for every batch. It is predictable, that processes will be created subsequently because of corrections, ...

It needs to be analysed, if this causes problems in the export, ...

![yearproceses01](https://user-images.githubusercontent.com/14835770/80344154-683c1b00-8867-11ea-9603-0d37ebd7d365.jpg)

**Comment by Kathrin-Huber** [comment]
@matthias-ronge we should add a check, if a year-level process is already in the system before creating one

**Comment by matthias-ronge** [comment]
I actually assumed that in this case the corrections would be carried out manually, i.e. the one missing process would be created, and then the link would be inserted manually in the annual file.

On the one hand, we had decided in the new implementation of the newspaper functionality, that we do not want to support the mode of subsequently modifying a newspaper that has already been created using the calendar. If we had wanted that, we would have had to program it quite differently. For example, the counted metadata (e.g. issue number) is no longer correct and would have to be corrected continuously everywhere.

On the other hand, there is the technical question of where the correct annual process should be found. The process title as a criterion seems to me to be unreliable.

Third, the postprocessing of the annual process must then be implemented again. When creating the newspaper, the individual issues are always added in chronological order, so that the correct calendar order is automatically created. If issues are inserted afterwards, the correct position must be searched by comparison so that the issues to be added are inserted in the correct position.

I don’t want to question of the proposed functionality. I just mention the things that come to my mind that we have to solve wisely.

**Comment by andre-hohmann** [comment]
First of all, we have to make sure, that we have the same scenario in mind. 
For me, it is mainly about missing issues, for which processes have to be created subsequently, because they were found later, ... Corrections regarding metadata can be done in the existing processes of the issues. 

I do not know, how a process for a missing newspaper-issue can be created without the use of the calendar, because the doctype, identifier to host, ... have to be captured correctly. 
Then, a process for the year is created, too. Thus, the additional "year-process" has to be deleted and the "old" one has to be modified? Is that possible? In the metadata editor, the issues (also volumes) cannot be modified. 

The metadata like the number of the issue, dates, ... should have been captured correctly before, so that a "space" is left for number of the missing issue. That should not be a problem. 

The technical aspects, i cannot assess. 

For me, it is most important, that the export is correct. Du to other problems, i cannot test that. 
But of course, i will be glad about consistent data in Production, like for example one year-process. If the functionality is possible with several ones and if this is technically more realistic, it has to be so.

**Comment by Kathrin-Huber** [comment]
This should work now, @andre-hohmann  can you confirm this?
please test with a new (newspaper) process, as old ones are created in the wrong way

**Comment by andre-hohmann** [comment]
Unfortunately, i cannot confirm it: 

![newspaperyear01](https://user-images.githubusercontent.com/14835770/89639634-3b5bc300-d8ae-11ea-8264-5bdc80e262df.jpg)
