### ISSUE TITLE
ORDER attribute is not correctly set in case of several issues per day

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3635]
### Problem
In the element `<mets:structMap TYPE="LOGICAL">` of the exported METS-file for the issue, the attribute @ORDER is not set correctly. This has been used in Kitodo.Production 2.x to qualify several issues per day. In Kitodo.Production 3.x, each issue is assigned the value 1. 

### Solution
The attribute @ORDER should contain the current order number, when several issues do exist per day. 

#### Examples 3.x
DresKr_880547324-1850100402_02-o.xml
- `<mets:div ID="uuid-ccf45eaa-66c2-4984-aeec-3c6cbbf83aeb" TYPE="title_page" ORDER="1"/>`

DresKr_880547324-1850100402_02-o.xml
- `<mets:div ID="uuid-a169f2e2-f506-43a0-b9d2-113d8d35e273" TYPE="title_page" ORDER="1"/>`

#### Examples 2.x

- `<mets:div ADMID="AMD" DMDID="DMDLOG_0182" ID="LOG_0313" LABEL="01-Sonstiges" ORDER="1" TYPE="issue" ></mets:div>`
- `<mets:div ADMID="AMD" DMDID="DMDLOG_0182" ID="LOG_0313" LABEL="02-Vesper" ORDER="2" TYPE="issue" ></mets:div>`

- https://digital.slub-dresden.de/oai/?verb=GetRecord&metadataPrefix=mets&identifier=oai:de:slub-dresden:db:id-880547324-1936091901
- https://digital.slub-dresden.de/oai/?verb=GetRecord&metadataPrefix=mets&identifier=oai:de:slub-dresden:db:id-880547324-1936091902

**Comment by matthias-ronge** [comment]
I don't know exactly, but as I understand it, the `ORDER` attribute is used internally to manage the order of structural elements and pages in the composite structure tree. I suspect that even if the `ORDER` attribute is correctly assigned when creating newspaper processes, this would be overwritten when using the metadata editor, but I'm not sure. @solth and @oliver-stoehr, what exactly happens there?

_Maybe possible solutions:_ Either that can be corrected in the XSLT (by simply counting) or code has to be written that just bends it when exporting. In the worst case, the logic used in the composite structure tree cannot be used in this way.

**Comment by andre-hohmann** [comment]
1. The ORDER-attribute is neither used in Kitodo.Presentation 2.x nor in Kitodo.Presentation 3.x. 
2. The ORDER-attribute has not been set in the processes which were created before the implementation of the "season-feature". 

Thus, it does not seem very important. Nevertheless, it might be possible that questions arise by users, who applied the attribute. 

I remove the blocking label. If someone needs the attribute, a metadata-element needs to be configured, filled out and transformed into the ORDER-attribute by XSLT.

**Comment by matthias-ronge** [comment]
Hi @andre-hohmann! If I understand it correctly, this use of the ORDER attribute according to METS is incorrect anyway, because (if I remember correctly what @sebastian-meyer said) the ORDER must be unique within the entire METS document. Accordingly, the ORDER attribute should not be used on the logical structure at all (or, it must be aligned with the ORDER numbers of the physical structure so that there are no duplications).

@oliver-stoehr, you have introduced setting the ORDER on the logical structure in the structure panel lines [1158](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/StructurePanel.java#L1158) and [1277](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/StructurePanel.java#L1277). What for?

**Comment by sebastian-meyer** [comment]
The `@ORDER` attribute has to be unique _within a structural map_, but not globally for the whole METS file. In other words: You can use the same `@ORDER` value twice as long as it occurs in different `mets:structMap`. So there can be a _logical_ structure with `@ORDER="1"` and a _physical_ structure with `@ORDER="1"`.
