### ISSUE TITLE
All processes selection should be possible for one or all table pages

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3747]
If you click on Checkbox button all pages selection, it is not clear whether all hits in the page are selected or on all pages. (Right now, it's the former.) For Kitodo script applications, the latter should also be important.

![Screenshot of select-all check box](https://user-images.githubusercontent.com/3040657/84129119-d61c5a80-aa41-11ea-888c-aa15b53c4367.jpg)

**Suggestion:** When the checkbox is checked, if it has more than one table page, a selection with options appears: all hits on this page, entire hit set.

Example (small):

![Example 1](https://user-images.githubusercontent.com/3040657/84129165-e7656700-aa41-11ea-8b60-f441c9df9da0.jpg)

Example (large):

![Example 2](https://user-images.githubusercontent.com/3040657/84129190-ec2a1b00-aa41-11ea-9775-69e42e29d77f.jpg)

**Comment by matthias-ronge** [comment]
Just thinking: JSF supports three-state checkboxes: They can be unchecked, semi-checked or checked. Could also be implemented as: If no process is selected, clicking the select-all checkbox turns it semi-checked, and all processes _currently visible_ are checked. If some processes are selected (may also be happened manually) the checkbox shows semi-checked, and clicking it in this state selects _all_ hits from the search. If _all_ hits are selected, the checkbox is checked, and clicking the checkbox deselects all. This would prevent menus, which may be found annoying.

**Comment by andre-hohmann** [comment]
I like your suggestion with the menu to select "Alle Treffer dieser Seite" and "Gesamtes Trefferset". It it easily understandable and the risk of misinterpretation is very low.

**Comment by markusweigelt** [comment]
@andre-hohmann Is the selection "Alle Treffer dieser Seite" used, or you can generally switch here so that the "Gesamtes Trefferset" can always be selected with the available checkbox. The problem with behavior is, it should be used everywhere
and possibly there are cases where the selection "Alle Treffer dieser Seite" is used.

@matthias-ronge I thought the tri-state checkbox is a good idea, but is not directly possible for Primeface DataTables. However, we could implement such a checkbox here using JavaScript.

![image](https://user-images.githubusercontent.com/3832618/135256288-a887a7f8-c0a5-4777-96a1-68a39485bedb.png)

@andre-hohmann Or do you still prefer the dropdown?

**Comment by andre-hohmann** [comment]
I use mostly "Gesamtes Trefferset", but i can imagine, that other users also use "Alle Treffer dieser Seite". Unfortunately, we have often the problem, that we cannot estimate the behaviour of all users. I suggest to offer both options, if it is possible. 

I prefer the drop down-option, because it is clear for everyone, what will happen. The checkboxes can be misinterpreted without any explanation.
