### ISSUE TITLE
[IP] Make shell scripts more generic

### ISSUE THREAD

**Issue by sebastian-meyer** [kitodo/kitodo-production#38]
The shell scripts provided in Goobi/scripts/ should be more generic. For example they should not assume that for every user in Goobi there is a corresponding local unix user.
- [ ] script_createDirUserHome.sh
- [ ] script_createDirMeta.sh
- [ ] script_createSymLink.sh
- [ ] script_deleteSymLink.sh

**Comment by matthias-ronge** [comment]
It is not really clear what is to be achieved here. It is a feature that a separate user directory is available for each user, so that each user only sees the links to process directories in his or her user directory that he or she should also work on. If this is not desired in a particular institution, the scripts can still be customized locally.

**Comment by matthias-ronge** [comment]
I close this ticket as no longer understandable, which is the need here.
