### ISSUE TITLE
Where to find METS Pointer Path of project settings

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3827]
I have checked the parameter created during export as additional meta data based on this project setting:
![metspointerpath](https://user-images.githubusercontent.com/61045115/87060863-4d910580-c20b-11ea-939b-7b3338a965a9.png)
I can find all parameters in the XML given to the export xslt process besides "METS Pointer Path".
This is not given there.
Could you please check, how to get this parameter (or maybe not needed anymore)?

Here you see all project settings (besides the METS pointer path):
![allprojectsettings](https://user-images.githubusercontent.com/61045115/87061161-b4162380-c20b-11ea-889c-0c1f6b153759.png)

**Comment by andre-hohmann** [comment]
Please see https://github.com/kitodo/kitodo-production/wiki/Bearbeitung-Projekte#mets-parameter for further information. It is for Kitodo.Production 2.x, but in general similar.
In general, you do not use the kitodo-metadata, but clear textual values. In Kitodo.Production 2.x it was not possible to configure the METS-metadata. This was the only way to enter the METS-Elements - except of the license - for the DFG-Viewer. 
Now it can be helpful, if the logo or contact address differs in the projects, as the project might not be identified by the metadata. Otherwise some or many of the parameters could be configured in the export-XSL and are thus not needed anymore here. 

In "METS Pointer Path" you have to "build" the path of the METS-file of the higher element, for example the periodical. The value depends on the structure of the path, where the file can be found, which differs in each institution. For example:
- `https://digital.slub-dresden.de/data/kitodo/(processtitle)/(processtitle).xml`

As far as i know, this is necessary or at least i have no idea how to create it by XSL.

**Comment by stefanCCS** [comment]
Many thanks for providing this information.
I think, I have understood the general concept of setting some METS-project-settings, which are Kitodo-internal handled as metadata und therefore can be written during export with help of of the xslt to the METS-values needed for the DFG-Viewer.

Concening the METS-Pointer, I have the feeling, that this is a not needed anymore, as in Kitodo 3 this basic METS-Path in configured in the folders, see image below.
Please check, if this a kind of "duplicate", which is not needed anymore
![mets-path](https://user-images.githubusercontent.com/61045115/87283739-e7033480-c4f5-11ea-9560-eba94305b51a.png)

**Comment by andre-hohmann** [comment]
It is not a duplicate. 
- The "METS path" in the configuration of the folders is the path of the image-folders. 
- The "METS Pointer Path" in the METS parameter is the path to the superordinate document as for example the peridocal, multivolume, newspaper.

**Comment by stefanCCS** [comment]
I am sorry, but I still do not understand:
1) The general logic of using METS pointer path in context of hierachical processes (periodicals/issues)
2) Even worse, If I would understand this, I do not see any chance to use this parameter, as it is not given to the xslt processing during export
Maybe we can have a talk about this? (@Kathrin-Huber could bring us togehter, I think)

**Comment by stefanCCS** [comment]
No documentation here...
