### ISSUE TITLE
Meaning of project settings METS ContentIDs, and METS PURL, METS Pointer Path unclear

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#3829]
In the project settings there are parameters, which have a clear definition in [METS-Profile](http://dfg-viewer.de/fileadmin/groups/dfgviewer/METS_application_profile_2.3.1.pdf).
But, the following parameters are not clear for me, especially, how to transform these during export:
- METS ContentIDs
- METS PURL
- METS Pointer Path
Please explain.

**Comment by andre-hohmann** [comment]
Regarding the _METS Pointer Path_: please see #3827.
Regarding _METS ContentIDs_ and _METS PURL_: it seems as nobody knows its purpose. I do not regard it in the configuration. 

Thus, i would not be worried about it. If we get some hints here, it should be possible to configure it afterwards.

**Comment by stefanCCS** [comment]
Well, understood - I can ignore it, of course.
@Kathrin-Huber : I would like to ask you to clarify, if METS ContentIDs and METS PURL are really needed,
If not needed, I would propose to remove these two topics from the project settings UI.

**Comment by andre-hohmann** [comment]
As it is difficult to clarify if the elements are needed (maybe the ones using them are not aware that they are using them), i suggest to keep them for the moment and to concentrate on the other issues. It could take a lot of time.

**Comment by stefanCCS** [comment]
Also fine for me.
@Kathrin-Huber : Please decide, if you want to keep this issue open (as reminder).

**Comment by matthias-ronge** [comment]
I just looked it up in the UGH: The value from the _METS PURL_ field was output in 2.x in the logical `<structMap>` in the topmost `<div>` as the XML attribute `CONTENTIDS`. The value from the _METS ContentIDs_ field was output in 2.X in the physical `<structMap>` at each (!) `<div>` as an XML attribute `CONTENTIDS`. The latter somewhat coincides with what I remember: It was apparently introduced in 2.x to support granular URN. That means the assignment of an unchangeable URN per structural element. However, URN granular was no longer pursued by the DNB because it seemed too complex in its administration.

The implementation in 2.x was unsuitable for this in two respects: The same _METS ContentIDs_ value was assigned to each physical `<div>`, and these had to be subsequently converted to individual identifiers using an external program. Second, URN requires that each URN continuously references the same entity, which means that the URN must also be carried along with subsequent insertions, a functionality which would also have to be provided by the external program. (To be clear: It is not enough to just count the DIVs. When you insert one later, it must be given a new number, the following ones must keep their original URN. When replacing an image, only the new image has to be given a new URN. All that was _not_ implemented in 2.x).

For me, at the moment the **goal** seems to be to **remove these input fields in 3.x as there is no requirement for them**.

**Comment by stefanCCS** [comment]
fine for me, of course
@Kathrin-Huber : Please decide, how to go on with this issue..

**Comment by stefanCCS** [comment]
No further topics to be done in this issue ...
