### ISSUE TITLE
doctypes missing in kitodo_opac.xml

### ISSUE THREAD

**Issue by mnscholz** [kitodo/kitodo-production#3852]
Commit 2bc1e73a7eb removed the doctypes section from kitodo_opac.xml.
This leads to the error message "No doctypes configured in opac.xml" when creating a new process.
The message, however, doesn't seem to have any effects. The process creation works as expected.

After a bit of debugging, I found out that org.kitodo.config.ConfigProject.getDocType() still reads the section via de.unigoettingen.sub.search.opac.ConfigOpac.getAllDoctypes(), despite the comment that doctypes section is legacy.

I'm working on commit 7b420843c (2020-07-03) but the above mentioned methods are unchanged, so the message should also show up in the latest version.

**Comment by matthias-ronge** [comment]
I admit we removed the doctypes a bit too hastily. They are still used at the moment, namely when generating the process title. In manual process creation, this primarily results in the error message you described, but when creating automatic processes (as it is used for newspapers), nothing works anymore.

For clarity: As solution of this ticket, the doctypes are returned temporarily and in a simplified form, where the solution for #3870 should be that the process title and TIFF header generation has to be rewritten, so that the doctypes can be removed.
