### ISSUE TITLE
Calendar editor missing confirmation when deleting blocks

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3864]
If a block is deleted in the calendar editor, no query appears.

**Goal:** Question box with message `calendar.block.remove.query` (_Do you want to delete the episode?_) should be shown.

**Comment by solth** [comment]
But removing a calendar block does not actually delete any processes or anything else until the "Create processes" button is clicked, does it? Therefor I would suggest to stick to our established UI interactions where confirm dialogs are only displayed if the user is about to change the persisted data in the database (for example when when deleting a process from the process list).

After all, for the same reason we do not have confirmation dialogs in the metadata editor when for example removing structural elements, because no data is changed on the hard drive until the user clicks the "Save" button.

**Comment by matthias-ronge** [comment]
You cannot delete any processes with the calendar editor. These are always issues for which processes should first be created. But a lot of information can be attached to a block, all of which you may have already laboriously entered. In 2.x there was a security question here. That's just what I noticed. If that's a design decision not to check back here, you can close the ticket.
