### ISSUE TITLE
Suppress browser suggestions in the date output

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3867]
When entering the date in Firefox, the calendar is covered with internal suggestions when you start writing. At least that looks bad.

![Browser suggestions](https://user-images.githubusercontent.com/3040657/88662315-14490880-d0da-11ea-9309-c638e826d6c2.jpg)

**Goal:** Suppress browser suggestions for fields with JSF calendar that folds out.

**Comment by henning-gerhardt** [comment]
If someone is faster in typing the date or need to use the same date for different newspapers than choose it from the calendar, than you force him to use the calendar and make him slower to enter the date. 

Maybe the calendar should be pop out on the right side of the input field instead of button side? Then can you choose the date from calendar or use the browser suggestion.

**Comment by matthias-ronge** [comment]
That would also be an option. However, the date of a block is the same for two newspapers is highly unlikely.
