### ISSUE TITLE
Calendar editor redirects to indexing page

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#3869]
When you start creating issues from the calendar editor, confirming the dialog with “yes”, the page “Indexing” is shown. It looks like that the idea was to go to the task manager (which would make sense) but the wrong tab is selected. (I previously indexed in the same user session.)

**Goal:** When navigating to the task manager, select the correct tab to show.

**Comment by solth** [comment]
Apparently, the user is not always send to the "Indexing" tab, but to the last tab the user had open on the system page. This is caused by our `MigrationsForm` (which manages the `activeTabIndex` for the system page) being `ApplicationScoped`, so that the last active `tabIndex` is kept even when the user leaves the system page.
