### ISSUE TITLE
Size of metadata field does not adjust to content

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3882]
### Problem
If a metadata field contains a long content, it is adjusted in the height to the content. 
If the metadata area is expanded, the height remains, although only one line is needed. 
This leads to more scrolling, ...

### Solution
The metadata field should be adjusted to the content - also the height. 

### Examples

![metadatafield01](https://user-images.githubusercontent.com/14835770/89011777-42fcf400-d311-11ea-929d-c20d7d3b1864.jpg)

![metadatafield02](https://user-images.githubusercontent.com/14835770/89011782-455f4e00-d311-11ea-9e36-41c75df099c5.jpg)

**Comment by matthias-ronge** [comment]
The distinction, whether it is a one-line text field or a multi-line text field, can be set in the ruleset with the `<setting multiline="false"/>` or `<setting multiline="true"/>`. In the generated HTML, these are two different elements, `<input type="text">` or `<textarea>`. A dynamic height adjustment only makes sense for the second, but there should also be a larger height from the start so that you can visually distinguish which type of input field it is. Please note that this produces very long fields for very long text content (e.g. abstracts). Is it wanted like that?

**Comment by andre-hohmann** [comment]
I do not want to change the type of the field - it is absolutely fine as it is. I just wander, if the height of the field could be adjusted to the content of the field. 

If, for example, the area of the metadata is widened before the metadata field with much text is shown, the field is adjusted to the content of the field. 
If this adjustment is not possible, there should be no other changes and this issue can be closed. 

![metadatafield01](https://user-images.githubusercontent.com/14835770/89262509-fc203e80-d62f-11ea-8caa-4bd82522d520.jpg)

**Comment by andre-hohmann** [comment]
The problem can be solved, when the current structure element (here: Heft/Ausgabe) is selected again. 
The issue will be closed.
