### ISSUE TITLE
Creation of processes for newspaper issues: Depiction of button "Add metadata" 

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#3974]
### Problem
If metadata is captured for the newspaper issues, the button "Add metadata" is hidden after the first metadata was captured. It has to be scrolled down, until the button is shown again. 

### Solution
The button "Add metadata" should be depicted next to the button "close", which is always shown. 

### Examples
The button is not shown
![issue01](https://user-images.githubusercontent.com/14835770/91266405-7f393e00-e771-11ea-8078-6a524f9a7087.jpg)

After scrolling down, the button is shown
![issue02](https://user-images.githubusercontent.com/14835770/91266411-82342e80-e771-11ea-9a15-aa2562304ad2.jpg)

The button should always be shown
![issue04](https://user-images.githubusercontent.com/14835770/91266898-76953780-e772-11ea-9907-f91669e8257d.jpg)

**Comment by oliver-stoehr** [comment]
The button was placed inside the scrollable area by design, because there can be multiple "add metadata" buttons.
When multiple issues occur on the same date, every issue has its own button to add metadata to this specific issue.
(The buttons are placed at the end bottom of the corresponding issue's area.)

**Comment by andre-hohmann** [comment]
OK, thank you - i did not regard the creation of several issues. 
I will check, if there is another possible solution to add metadata more conveniently.
