### ISSUE TITLE
Unwanted renumbering for pages (order) in meta data editor

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#4006]
Lets assume I have the following structure:
<img width="144" alt="Numbering-1" src="https://user-images.githubusercontent.com/61045115/94035450-5c776500-fdc3-11ea-8716-fbcbaa774576.png">
Now I link the page 3(III) to Chapter 1, then I get:
<img width="157" alt="Numbering-2" src="https://user-images.githubusercontent.com/61045115/94035498-6f8a3500-fdc3-11ea-8e1f-cf733b2feeac.png">
--> looks liks a renumbering is performed, which in my opinion is wrong (the physical order should still be the same)

**Comment by oliver-stoehr** [comment]
This renumbering is done by design. The combined structure tree of Kitodo 3 should provide an easy way to reorder pages, where the logical and physical order of the pages is the same. Therefore this changes the structLinks _and_ the order in the physical structMap.
For more complex actions where the order of the assigned pages should differ from the order in the physical structMap the separate structure trees should be used in the metadata editor.

**Comment by stefanCCS** [comment]
Understood, usage of split view is ok.
