### ISSUE TITLE
Structure tree should show image number (or name), not internal order number

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4038]
In the example, pages 2-6 are to be added to the new structure element.

![Screenshot 1](https://user-images.githubusercontent.com/3040657/95461441-865d8980-0976-11eb-9973-9defe6b6a673.png)

![Screenshot 2](https://user-images.githubusercontent.com/3040657/95461454-89587a00-0976-11eb-9c72-74e9daf553fb.png)

The number displayed has changed. Picture 2 is now picture 1, and picture 1 is now picture 6. In short, you cannot use the (changing) numbers as a guide to identify the index of the scanned picture (and the continuous book, from front to back).

![Screenshot 3](https://user-images.githubusercontent.com/3040657/95462617-0801e700-0978-11eb-970d-420f07befff5.png)

**Goal:** In front of the colon, the canonical part of the file name without leading zeros should be displayed, not the internal order number. Then you would always know where you are.

**Comment by andre-hohmann** [comment]
I strongly support this suggestion. The current behaviour is very confusing. 
From my point of view, the combined structure will be much more usable if Matthias goal is reached.

**Comment by BartChris** [comment]
@matthias-ronge 

We also encountered this behaviour. I made some internal changes to display the images names in the structure tree. However i am not sure in which places the image name should be displayed. Apart from that i am no expert in JSF so i am hesitating to make a pull request here. So here just for reference the changes i did. Hopefully someone can adress this soon in the master because it really improves the editing experience:

Changes in StructurePanel.java:

old:
https://github.com/kitodo/kitodo-production/blob/61f0b530b3013b7c3ffc2499be49faad0dcf9d31/Kitodo/src/main/java/org/kitodo/production/forms/dataeditor/StructurePanel.java#L540

```
    private String buildViewLabel(View view) {
        String order = view.getMediaUnit().getOrder() + " : ";
        if (Objects.nonNull(view.getMediaUnit().getOrderlabel())) {
            return order + view.getMediaUnit().getOrderlabel();
        } else {
            return order + "uncounted";
        }
    }
```
new:
```
import org.apache.commons.io.FilenameUtils;

private String buildViewLabel(View view) {
        URI uri = view.getMediaUnit().getMediaFiles().entrySet().iterator().next().getValue();
        String fileName = FilenameUtils.getBaseName(uri.getPath()) + " : ";
        if (Objects.nonNull(view.getMediaUnit().getOrderlabel())) {
            return fileName + view.getMediaUnit().getOrderlabel();
        } else {
            return fileName + "uncounted";
        }
    }
```

Result:

![grafik](https://user-images.githubusercontent.com/7516499/117693268-248c2900-b1be-11eb-923a-234fe2d419be.png)

This also brings up the question on wether "non advanced" mode of the metadata editor should be adapted, too. Especially given the fact that there are difference in functionality between the two eding modes:

https://github.com/kitodo/kitodo-production/issues/4380

**Comment by BartChris** [comment]
It seems to work. I issued a pull request.

**Comment by solth** [comment]
I am not sure the proposed changes are correct. It seems there is a misunderstanding about how pages - and structures, for that matter - are ordered in Kitodo 3. 

AFAIK, the filename determined the physical order of pages in Kitodo 2. In that case displaying the canonical part of the filenames makes sense. In Kitodo 3 however, the ordering of pages and structure elements is solely defined by the `ORDER` attribute of the elements within the METS structure (which allows for arbitrary filenames where one does not have to worry about impacting page order by accident). This attribute is **initially** determined by the sorting of the filenames in the files ystem (which - I think - can vary between operating systems and therefor isn't a good indicator for physical page order anyway).

Whenever the user moves a structure element (or individual pages) however, the `ORDER` attribute (and the position of the corresponding `mets:div` elements in the physical structure map as well as the order of `smLinks`) is updated accordingly, representing the new _physical_ order of the pages. Therefor, the filenames are completely irrelevant when visualizing the order of pages in a document (apart from the first time a process is loaded and saved in the metadata editor), and the proposed changes would falsely imply otherwise.

I think the problem stems mainly from the current position options for new structure elements being limited to "First child", "Last child", "Previous sibling" and "Next sibling", all of which implicitly result in assigned pages being moved correspondingly and therefor receiving new `ORDER` attributes. 

IMO, the changes in #4365 will greatly reduce the confusion, because allow creating new structure elements from selected pages in their "Current position" _without_ _reordering_ _the_ _pages_.

**Comment by BartChris** [comment]
Thank you very much for the detailed explanation. Since the other options for adding structure elements would still be there after your changes are merged: would it maybe  be possible to show both- the orderlabel AND the original image name? I do not know how the display of the Information would look like, but that would reflect the internal Kitodo structure and also avoid confusion on the user's side as outlined above.

**Comment by matthias-ronge** [comment]
The solution is the right one for the problem described. What you describe, @solth, is true in theory, but in practice there is another implication: For a user, a page has two properties, the number of the scan from the file name, and the pagination. The number from the file name corresponds to the physical sequence, except for later scanned corrections which may have a higher number than the image of the back cover, which is typically easy to find because it is optically very different (often with a color checker). The filename (number) is very important for the user to see, because only from it he can notice **whether he has accidentally dragged pages into the wrong order**, if the physical medium is not available for him when structuring and the book has no pagination in this page range. The internal order number is irrelevant for the user to see. It is always correctly assigned by Production, and the user can tell the _current_ order of the images from looking on them. 

#4202 is no replacement for this requirement.

**Comment by solth** [comment]
@matthias-ronge Yes, would you describe is true for Kitodo 2, but not for Kitodo 3, if I understand it correctly. That's what I tried to explain in my previous comment: the "internal" `ORDER` _is_ the physical order of the pages, no matter how the files are named! That's why it is correct to display the `ORDER` and update it on drag'n'drop operations (which weren't available in Kitodo 2, IIRC?).

> The internal order number is irrelevant for the user to see. It is always correctly assigned by Production, and the user can tell the _current_ order of the images from looking on them.

That's what I thought initially, too, "the pages are just continuously numbered in the tree and therefore the number does not need to be displayed". But after it became obvious that the order of pages and sibling structures is not easily visible in the gallery alone (see #4368 ), the relevance of displaying the `ORDER` - at least in the gallery - became a little clearer to me. Without it, there is currently _no_ way to tell if there is a structure element between to pages on the same level when just using the gallery.

I have a suspicion this topic might go a little deeper and is a conceptional issue. Would you mind transforming this issue into a 'Discussion' (see button/link right below the 'participants' of this issue) so we could discuss it before coming to a conclussion what the real issue is that needs to be addressed?

**Comment by andre-hohmann** [comment]
I want to support @matthias-ronge point of view in the comment before, especially: 

> The filename (number) is very important for the user to see, because only from it he can notice whether he has accidentally dragged pages into the wrong order, if the physical medium is not available for him when structuring and the book has no pagination in this page range.

As i only work without the original resources, it happend several times, that i could not clearly identify pages without pagination, because the number in the structure tree changed as soon as new structure elements were created, pages were moved, ...
If each image had a pagination number, it would work and often, i did it to ensure that the order and the assignment to structure element is correct. It is difficult to explain, but if you try to structure a process without the original and you have several pages without pagination, you will quickly understand the problem. 

@solth suggestion to open a new issue for the underlying problem is very good. I think that is the problem, which @sebastian-meyer pointed out, when we discussed about ORDER, ORDERLABEL, ...

**Comment by solth** [comment]
> I strongly support this suggestion. The current behaviour is very confusing.

@andre-hohmann could you test the changes in #4365 ? I would hope that adding structure elements and assigning selected pages would be much less confusing with those changes, too. I think @subhhwendt already tested those changes successfully.

Additionally, I would suggest to deactivate all other positions at which a new structure element can be inserted - "First child", "Last chilc", "Previous sibling", "Next sibling" - when creating a new structure element from selected pages, so that structure elements from pages can only be created "in place", in order to avoid implicit re-ordering of those selected pages. Could that further ease the pain?

**Comment by matthias-ronge** [comment]
The label is correctly formed and displayed in the structure tree since the pull request #4642. The same should be done here (call `DataEditorForm.getStructurePanel().buildViewLabel(View)` to get the correct label).

**Comment by andre-hohmann** [comment]
I opened a new issue for the problem which is described in https://github.com/kitodo/kitodo-production/issues/4038#issuecomment-939979953. 

- #5031 

I close this issue, because the original problem described by @matthias-ronge has been solved. 
The new "problem" should be analysed separately.
