### ISSUE TITLE
Search by task title returns wrong processes

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#4272]
If you want to search for all open tasks called "LZA Archivierung" you get even processes returned where tasks open with title "LZA Validierung nach dem Scannen" or "LZA Validerung vor dem Export" because the search did not use the used title as one search term and use both words as separated search terms.

**Comment by matthias-ronge** [comment]
This is a point that should be taken into account when reimplementing search engine integration. Essentially, it is about the tokenization of the task titles. Should be searched for `LZA` AND `Archivierung` (which includes titles with the terms `LZA`, `Archivierung`, `vor`, `dem`, `Export`) or should be searched for `LZA Archivierung` as a single term (which is inequal to a single term `LZA Validerung vor dem Export`). Also take into account that less tokens produce a smaller index, because a list of matching documents is held for each token.
