### ISSUE TITLE
Doubling nested metadata entries does not copy the values

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4284]
Doubling nested metadata entries:

![Entry to duplicate](https://user-images.githubusercontent.com/3040657/111280294-efd77780-863b-11eb-9d10-45cf29813f38.png)

The entry has been doubled, but without the data in it:

![Second entry has no values](https://user-images.githubusercontent.com/3040657/111280368-08479200-863c-11eb-8713-e1fad4572760.png)

**Goal:** When duplicating nested entries, also duplicate the values.

**Comment by solth** [comment]
I _think_ this is caused by https://github.com/kitodo/kitodo-production/blob/b84748003af41b26cfd2e77b62423f2eb5ec8820/Kitodo/src/main/java/org/kitodo/production/forms/createprocess/ProcessFieldedMetadata.java#L408 the `MetadataGroup`/`ProcessFieldedMetadata` is copied including its included metadata children, but only the treenode for the copied `MetdataGroup` is created, not those for the included child metadata elements.

**Comment by matthias-ronge** [comment]
`ProcessFieldedMetadata` is duplicated. This looks wrong to me. I think, the metadata group would need to be duplicated instead, and then rebuild the metadata table.
