### ISSUE TITLE
Workflow creation and changes - Additional Dev-Mode to allow for more flexibility

### ISSUE THREAD

**Issue by BartChris** [kitodo/kitodo-production#4334]
Hello,

i am wondering wether it could be an improvement to allow easier changes on already activated workflows while one is in development/testing of workflows. 
I do not know wether there are some hard restrictions which do not allow to change an already activated workflow but while testing, sometimes it is necessary to do a single little change (adding a parameter to a script) to an existing workflow. Right now it is necessary to copy the workflow and create a new one. It would be nice if there would be a dev mode where the user can easier make changes to workflows.

**Comment by matthias-ronge** [comment]
The background is that workflows are intended to be used across projects. If a user changes a workflow that is also used in a project to which he or she has no access, that would influence the other project. For this reason, workflows from which processes have already been generated, may no longer be edited.

A function of varying a workflow (as a copy) and then migrating existing processes to the new workflow is a desideratum. But we are still missing it at the moment. So I would like to treat this issue as a <kbd>feature</kbd> request. 

**Goal:** Implement the option to migrating existing processes to the new workflow created as a copy from the initial one.

An imaginable approach would be:

1. The user creates new workflow by cloning an existing workflow (from which processes were created)
2. If the new workflow has been set active, the user can select which production templates are to be cloned. The cloned production templates get the new workflow instead of its predecessor, the other parameters remain.
3. The user can now migrate processes from one production template to the other. In doing so, he or she may have to resolve deviations, for example decide what happens to processes which are in an open step that no longer occurs in the new workflow. (Another requirement is that the process is not currently being worked on.)

**Comment by BartChris** [comment]
Thank you very much for your elaborated answer. This sounds reasonable. Of course one does not want the processes to be in an inconsistent state. Yout approach to solve that sounds good. 

However when you work on a test system, you often do not deal with data which needs to be preserved and migrated to the new workflow. Sometimes you are just testing a new workflow feature and do not care wether this has an effect on old testing processes which are no longer needed. So i suppose the situation is different between test and prodcution system.

**Comment by matthias-ronge** [comment]
Even on a test system, if editing the workflow would be possible, you would have to create a new production template from the changed workflow again, because technically, the data from the workflow is already fetched and converted in this moment, and stored in task templates of the production template. And then you would need to create a new process (which copies the data again, from the task templates to the tasks). TLDR, simply changing the workflow doesn't work.

For mere development purposes, there is also the way to change the parameters of a step of a process directly in the database. (It may require Tomcat restart or reindexing the processes, I don’t know without trying.)
