### ISSUE TITLE
Meta Data Editor - add keygroup in keygroup (which should not be possible)

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#4464]
Release 3.3 

If you have a structured keygroup in RuleSet (e.g. "person").
And you try to add a sub-key in this keygroup, you also get a choice in this "add-dialog" to add full keygroup (here "person"),
which leads to strange behaviour including destroying other parts of meta.xml !!!
![grafik](https://user-images.githubusercontent.com/61045115/121487984-ebb8bd00-c9d2-11eb-8bc9-fbee327f3f56.png)

-> Please check

**Comment by solth** [comment]
IIRC nested `metadataGroup`s are indeed allowed. The case you described seems to be caused by a ruleset where nested "person" `metadataGroup` elements are not specifically forbidden.

@matthias-ronge is that correct?

**Comment by stefanCCS** [comment]
If I can try out something with changes in the ruleset, please tell me.
Now my Rule Set looks as follows:

```
<key id="Person">					
	<label>Person (group)</label>
	<label lang="de">Person (Gruppe)</label>
	<key id="LastName">
		<label>Last name</label>
		<label lang="de">Familienname</label>
	</key>
	<key id="RoleCode">
		<label>Relationship designation (code)</label>
		<label lang="de">Beziehungskennzeichnung (Code)</label>
		<option value="rcp">
			<label>Adressat</label>
		</option>
       ...

<restriction division="Monograph" unspecified="forbidden">
	<permit key="Person">
		<permit key="RoleCode" maxOccurs="1" minOccurs="1"/>
	</permit>
        ...

```

**Comment by matthias-ronge** [comment]
No, only those subkeys that are declared in the rule set are allowed within a key group. In principle, nested key groups are allowed, but then they have to be declared that way. Example: An indication of the provenance (group) contains a person (group) with several keys.

It looks like something is going wrong with the recursion here.

The general (bottom left) <kbd>+</kbd> button should offer the _addable metadata_ of the `StructuralElementViewInterface`, the <kbd>+</kbd> button of a group should offer the _addable metadata_ of the `ComplexMetadataViewInterface` for this group. (This applies recursively for a group containing a group, containing a group, …)

Note that the `StructuralElementViewInterface` for this purpose `extends ComplexMetadataViewInterface`, so the dialog should generically receive a `ComplexMetadataViewInterface` as a parameter, which can be the `StructuralElementViewInterface` in case of the general <kbd>+</kbd>.

The intended implementation is: the dialog should display the list it can obtain from `getAddableMetadata(Collection<Metadata> entered, Collection<String> additionallySelected)`. It contains the addable keys along with their labels translated in the metadata language of the user and sorted as required by the ruleset. `entered` is the metadata of the group in question (to check if `maxOccurs` limits are reached, in that case, a sub-key should not be offered again), `additionallySelected` lists all fields that the user has already added (by previous invocations of the <kbd>+</kbd> dialog) but has not yet entered metadata in it, so that they are not yet part of `entered`.

The result of the dialog is the key to be added, which is then to be added to the `additionallySelected`, then `getSortedVisibleMetadata(Collection<Metadata> entered, Collection<String> additionallySelected)` is to be invoked again to produce the new group information with the requested empty (or maybe filled with presets, as the ruleset declares) fields in their correct sorting position.

Looking into the code, it feels wrong to me how the object is obtained, on which `.getAddableMetadata(…)` is invoked. It should be obtained from the `ProcessFieldedMetadata` (of the metadata view in its whole, or for the group. Both are backed by a `ProcessFieldedMetadata`):

    ComplexMetadataViewInterface metadataView = ((ProcessFieldedMetadata) selectedMetadataTreeNode
            .getData()).getMetadataView();

(There is no `public ComplexMetadataViewInterface getMetadataView()` in `ProcessFieldedMetadata` yet, it must be added.)

**Comment by stefanCCS** [comment]
Even if I do not understand anything ;-) -  it looks like that we have a Bug and not a misconfiguration on my side.
Correct?

**Comment by matthias-ronge** [comment]
Yes, its a bug 🐞 and there seems to be a whole nest of bugs: 🐞 #4285 🐞 #4457

**Comment by solth** [comment]
It seems this also causes regular metadata keys to not show up anymore reliably for nested metadata groups after a few hierarchical steps, so this is an even more severe problem.
