### ISSUE TITLE
"Current position" is misunderstandable

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4477]
The dialog about creating new docstructs speaks of children, parents, and the possibilities of creating a division before or after the current element. In this context, the possibility of _current position_ is misunderstood by the new operator in that the new division is created on the same level (like before or after the current element), but in fact a child level is added to the current element.

![Screenshot](https://user-images.githubusercontent.com/3040657/121657750-f5a8f180-caa0-11eb-8cde-cbdc50727af2.png)

**Goal:** Should be renamed to “As child in current position”.

Perhaps, the whole wording would have to be reconsidered. It makes sense if a division is selected, which is structuring, but if media is selected, it feels to me that some completely different wording would actually be needed.

**Comment by solth** [comment]
We should probably disable the "Position" selection in the popup dialog or - better - remove it altogether when creating structure elements from pages, since the implicit reordering of the pages when selecting any other position _but_ "Current position" is clearly unwanted (which we determined in the discussions in on other issues, if you recall). 
@andre-hohmann and @subhhwendt what's your opinion on that?

**Comment by matthias-ronge** [comment]
I would also agree with removing the selection in this case.

**Comment by andre-hohmann** [comment]
From my point of view, the "Position" selection can be removed, too. 

I have not much experience with it, but for my use cases, the "Current position" does what i expect.

**Comment by subhhwendt** [comment]
Thumbs up from Hamburg - for removal of the option dialog when creating structure element from pages! My colleague slipped in confusion - using one of the specific option.
