### ISSUE TITLE
Remove link from home directory as "possible action" does not work 

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4554]
### Problem
In the menu "possible actions" it is possible to chose "Remove link from home directory". If it is applied to several processes in a list, an error message and a confirmation message is shown: 

- Error loading 'Process' with ID 0
- Removed all folder from home directory: fertig/

However, the links are not removed. 

It is possible to remove the link for each process by the action button on the right side. 

### Solution
It should be possible to remove the links from the home directory with the action. 

### Examples
![homeverzeichnis02](https://user-images.githubusercontent.com/14835770/127325165-a4738869-cb87-44c7-b83f-f8d5cea4b984.jpg)

![homeverzeichnis01](https://user-images.githubusercontent.com/14835770/127325178-a3693a43-72d7-4dca-8cfb-42878683f2cb.jpg)

**Comment by matthias-ronge** [comment]
The called function `uploadFromHomeForAll` is totally independent of the selection! It will invoke `script_deleteSymLink` for all files in a folder named "fertig/" in the user’s home directory (`/usr/local/kitodo/users/testadmin/fertig/*`) Without an (unknown) special implementation of the script, this function doesn’t make much sense. From the internal names (upload, WebDav) I _guess_ that this special implementation of the `script_deleteSymLink` was meant to upload the files somewhere before deleting the folder.

My suggestion would be to remove this functionality altogether, because it is incomplete and not understandable, and write a simple function which just removes the symbolic links from the selected processes. The current implementation is also very inefficient, see #3448

**Comment by andre-hohmann** [comment]
This is comprehensible - thanks for the explanation. So two tasks can be derived from this issue: 
1. Remove the function "Remove link from home directory" completely from the list and in the code. 
2. Write a new function to remove the symbolic links from the selected processes. 

One question @matthias-ronge : Does the function "Link within home directory" work properly? Or is it also implemented inefficiently?

**Comment by matthias-ronge** [comment]
“Link in home directory” is perfectly fine. It just creates one link.

The problem when removing the link(s) is that the application doesn’t track where it created links, and thus guessfully tries to remove the link wherever it might be, where locations found on different paths are just handled again and again.
