### ISSUE TITLE
Wrong process title generation on newspaper migration

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#4564]
If you have a newspaper with several issues per day and every issue is created in 2.x as a separate process. Process generation in 2.x was 

`<shorted title aka ATS/TLS>_<catalog id digital aka PPN>-<YEAR><MONTH><DAY><IS ... first two letters of issue>_<ISSUE ... complete issue title> `

and an example for such a process title

`StaaHofM_1031939121-1844032901_01-p`

If a such process like above is the first process on migration then the created process title for the overall newspaper process and all newspaper year processes starts with

`StaaHofM_103`

instead of the expected 

`StaaHofM_1031939121`

process title. 

Finding this processes is difficult as you can only use the shorted title and not the catalog id digital which is more common.

If you are lucky and your first process of a newspaper looks like

`RadlunRa_411907697-18990115`

then you have no issues even if there are later processes for multiple issues for a day.

So far as I can say the complex regular expression in [NewspaperProcessesMigrator.java#L92](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/java/org/kitodo/production/migration/NewspaperProcessesMigrator.java#L92) is not cable of this kind of created process titles in 2.x. as 2.x has no restriction on how you are creating your process title for multiple issues per day of a newspaper.

**Comment by matthias-ronge** [comment]
In version 2, the `projects.xml` specifies what the newspaper process title looks like for each issue. That can vary, it would even have been possible to use different titles in several projects, I think. Since you can rename the title after the migration, and that only has to be done for the newspaper and the years (not the issues, so that’s not so many processes) the easiest way would be to fix it manually after the migration, if the result is unfortunate, and it only needs to be fixed onece. Programming a generic system here that is suitable for all cases is at least ornate.

**Comment by henning-gerhardt** [comment]
Manually renaming means over 100 processes to touch and this are only the processes for this newspaper title. Maybe there are more newspaper titles which get this issue.

I experimented a little bit with this regular expression and if I changed it from

`(?<=.)\p{Punct}*(?:1[6-9]|20)\d{2}\p{Punct}?(?:0[1-9]|1[012]).*$`

to

`(?<=.)\p{Punct}*(?:1[6-9]|20)\d{2}\p{Punct}?(?:0[1-9]|1[01]).*$`

it created with this newspaper title the correct or expected newspaper title. But I don't know what I'm really doing on changing this expression.

**Comment by matthias-ronge** [comment]
You removed december.

Your problem is a specific mismatch in the title

    StaaHofM_1031939121-1844032901_01-p
                └──┘└┘
                yyyymm

which should have matched here:

    StaaHofM_1031939121-1844032901_01-p
                        └──┘└┘
                        yyyymm

We could try `(?<=.)\p{Punct}+(?:1[6-9]|20)\d{2}\p{Punct}?(?:0[1-9]|1[012]).*$` but this will fail for institutions which don’t have a separator character before the date (however, that’s unlikely).

**Comment by henning-gerhardt** [comment]
I looked into your data and checked all existing newspaper titles which I could determinate and beside the already know title was there 3 additional newspaper titles which get a wrong process title after migration.

I "tested" your suggested change and it works for our data or the data I know about. I can not say if this change is correct for all possible values in our or other ones data.

**Comment by henning-gerhardt** [comment]
As the discussed changes is working for us, I will close this ticket. If someone other has an issue with this change, please reopen this ticket.

**Comment by andre-hohmann** [comment]
See also the following discussion: 
- https://github.com/kitodo/kitodo-production/discussions/5712
