### ISSUE TITLE
Users have no access to mets.xml

### ISSUE THREAD

**Issue by m-kotzyba** [kitodo/kitodo-production#4632]
If a user generates a `<ProcessTitle>_mets.xml` by using the "Export metadata as METS file to home directory" button, the `<ProcessTitle>_mets.xml` is generated but the user has no rights to do anything with the file. This is caused by keeping "tomcat" as file owner and group and do not set righs to others:

![003](https://user-images.githubusercontent.com/85474095/132167085-708f7b0c-1764-4b3f-bc47-e46fa6fe8dfd.PNG)

**Comment by matthias-ronge** [comment]
It has always been like this. Years ago this was not a problem because Tomcat only had a user, who was assigned to the _users_ group, and permissions `-rw-rw--r` were set for all files it wrote. This is more stringent in younger distributions. I'm sure you can reconfigure that somewhere…

Even so, I agree that the files should be written with reasonable permissions.

**Comment by m-kotzyba** [comment]
Thanks for the explanation! You are right, adding the relevant users on the server to the group `tomcat8` solved the issue.
