### ISSUE TITLE
User cannot change his own name, location or login

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#4652]
Currently, users without special permissions cannot change their own name, location or login. Instead, he requires the `editUser` authority, which in fact is intended for editing _other_ users. Instead, every user should be allowed to change this personal information without the need for some specific permissions.

<img width="1435" alt="Bildschirmfoto 2021-09-08 um 10 26 13" src="https://user-images.githubusercontent.com/19183925/132474567-9691c3fb-a4f1-4024-90a7-60255efcd4c9.png">

**Comment by matthias-ronge** [comment]
I don't like the idea at all that a user's login can be changed afterwards. Neither by the user himself nor by others. The reason is that underneath, the user login is also used for the Linux user. Maybe it even works in part, but I can only imagine that this leads to undesirable side effects in various places. For example, the home directory is no longer found and a new one is created. The old remains as a holdover. What if the user has meanwhile mapped a network drive while changing their login name? In case of doubt, this all leads to further problems in real-life operation and it should ideally not be possible at all.

**Comment by henning-gerhardt** [comment]
I have the same opinion like @matthias-ronge and would extend atleast the mentioned cases about two: 

- if an user is changing his ldap login name than this change must even changed into the ldap system and this is dangerous
- if an user is changing his login or ldap login name to an existing login or ldap login name - this must be avoided as then two users are "sharing" one login

**Comment by solth** [comment]
@henning-gerhardt I deliberately left out the "ldap-login" because I didn't want to imply any LDAP changes. My proposal is just for non-LDAP users!

I didn't think about the linux user and agree with @henning-gerhardt and @matthias-ronge that it may be difficult to make the "login" configurable. The other fields though - "First name", "Surname" and "Location" - should be editable by the user, though (again, for non-LDAP users)

**Comment by henning-gerhardt** [comment]
> "First name", "Surname" and "Location" - should be editable by the user (again, for non-LDAP users)

But then the stored data in database and ldap will differ which is - in my opinion - not a good solution.

**Comment by solth** [comment]
> But then the stored data in database and ldap will differ which is - in my opinion - not a good solution.

I wrote "for non-LDAP users", didn't I? What I mean by this is that those fields should only be configurable by users that only exist in Kitodo and are not imported from LDAP. For those installations where no LDAP server is used. (an additional Tooltip should be displayed in the LDAP case informing the user that he can't change his LDAP data via Kitodo)

**Comment by henning-gerhardt** [comment]
Thank you for the clarification.
