### ISSUE TITLE
Correction workflow - corrected processes not visible in task list

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#4766]
### Problem
After a correction message is send for a process, the process cannot be found in the task list. 
Only after logout/login, the process can be found in the task list. 
In the process list, the process can be found all the time. 

### Solution
Processes should be immediately shown in the task list after the correction workflow has been started.

**Comment by matthias-ronge** [comment]
Then the new behavior is wrong. Correction tasks are priority tasks. They are important. They should always be displayed, and always sorted upwards in the table. A filter can, if at all, hide other tasks.

**Comment by solth** [comment]
The current behavior is not per definition wrong, but just follows a wider establised paradigma for checkboxes: checking a checkbox should _either_ _always_ **hide** something (each selected checkbox restricts the list more) or _always_ **show** something (each selected checkbox augments the list). I opted for the second approach because it is more intuitive, IMO.
The simple solution should probably be to just set the corresponding checkbox for correction tasks by default.

**Comment by andre-hohmann** [comment]
I think we mean the same and i do not question the checkboxes. 

When the Checkbox-Filter "Correction tasks" would be activated by default, i think all get what they expect.
