### ISSUE TITLE
Can't authenticate via Ldap to a Windows Active Directory

### ISSUE THREAD

**Issue by joerg-liebenow** [kitodo/kitodo-production#4807]
By using firstname and lastname in the DN (LDAP-Gruppe->User DN-> cn={firstname} {lastname},ou=Benutzer,ou=Kitodo,...) 
it will be impossible to authenticate against a Windows Active Directory.

It seem's that the authentication using not the classes
org/kitodo/production/services/data/LdapServerService.java
but the "old" ldap classes 
org/kitodo/production/security/DynamicAuthenticationProvider.java
which not using replacing for firstname, lastname !?

One question is, is there a solution to configure the User DN, so that AD will accept them ?
If there is no trick to configure, why will not be used the function authentication in LdapServerService ?
Why exist the authentication (likewise code) twice ?

If there is no way to authenticate against the AD how about this solution to include the missing replacements in the 
function  authenticate(Authentication authentication) of DynamicAuthenticationProvider.java ?
##
95c95,98
<             configureAuthenticationProvider(ldapGroup.getLdapServer().getUrl(), ldapGroup.getUserDN());
---
>           String userDN = ldapGroup.getUserDN();
>             userDN = userDN.replaceAll("\\{lastname\\}", user.getSurname());
>             userDN = userDN.replaceAll("\\{firstname\\}", user.getName());
>             configureAuthenticationProvider(ldapGroup.getLdapServer().getUrl(), userDN);
##

**Comment by matthias-ronge** [comment]
For Active Directory authentication, you must put _Firstname Lastname_ in the „LDAP login“ field of the user record:

![Screenshot 2021-11-04 073017](https://user-images.githubusercontent.com/3040657/140268229-1f0eac4f-8834-4064-9bf1-8d553aec3045.png)

Production will then use this value to replace `{login}` in the User DN of the LDAP group. So, your User DN must then still look like:

    cn={login},ou=Benutzer,ou=Kitodo,...

**Comment by matthias-ronge** [comment]
I just looked at this again in the code before telling anything wrong here. Apparently there is also a `{ldaplogin}` variable that is replaced, but not from the login if I see it correctly. The programming of this part is very cumbersome, through several interfaces and confusing. So I think that I gave the correct solution with my answer above, but if that doesn't work, you could try again with the following User DN:

    cn={ldaplogin},ou=Benutzer,ou=Kitodo,...

Please let us know what exactly worked in the end.

**Comment by joerg-liebenow** [comment]
I tried your proposals and i try some alternatives too, but it won't work !

I find this error in the log:
##
05-Nov-2021 09:18:42.978 SCHWERWIEGEND [http-nio-10180-exec-7] org.apache.catalina.core.StandardWrapperValve.invoke Servlet.ser
        java.lang.IllegalArgumentException: can't parse argument number: ldaplogin
##

**Comment by matthias-ronge** [comment]
I looked again: It definitely does not work with `{ldaplogin}`. Only `{login}` [is searched for](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/java/org/kitodo/production/security/DynamicAuthenticationProvider.java#L155-L157), and replaced by `{0}`. That is the "argument number", the lack of which is criticized in the error message.

Please try again with

    cn={login},ou=Benutzer,ou=Kitodo,...

and look, what exception you get in the log. (You did fill in the „LDAP login“ field for the user you are trying to log in with, and did save the change, didn't you?)

Perhaps, in addition, something is broken there in version 3.  
I know that the authentication against MS Active Directory with version 2 works somehow, but I just don't know exactly what it had to look like, and I don't have an Active Directory myself to test it, unfortunately. If you don’t get along, you may also write this question on the mailing list, maybe there is another institution that uses AD auth successfully and that can tell us how the parameterization should look like correctly.

**Comment by joerg-liebenow** [comment]
To use the login is not really workable, because in our AD and for login, it will be an different usage !

A solution as we use at the moment is to change the Code in DynamicAuthenticationProvider.java as shown above !
I am not sure that this is so okay with the usage of spring security !?

**Comment by matthias-ronge** [comment]
Your change _should_ do exactly the same as entering _first name—space—last name_ in the _LDAP login_ field for each user, save, and sticking to `{login}` in the LDAP group configuration. There is an inner switch that prefers the value of _LDAP login_, if one is given there. It's not entirely clear to me why that doesn't work … :confused: As soon as I find the opportunity to do so, I will investigate it; and it should be documented. But that leads away from the topic.

In any case, in the LDAP related code, there are three places where variables are replaced, and each time a little different. This should be summarized so that all values are equally valid everywhere.

**Comment by matthias-ronge** [comment]
`{ldaplogin}` is not resolved. This is a bug.

**Comment by matthias-ronge** [comment]
To answer the initial question:

> which not using replacing for firstname, lastname !?

Production version 3 uses the Spring Security framework for authentication. Internally, the replacement happens inside the class `org.springframework.security.ldap.authentication.AbstractLdapAuthenticator` (a class from the Spring Security framework, not a class of Kitodo.Production itself − thus, not editable for us) which takes as parameter for authentication **one** username string. When using `{ldaplogin}`, this requires internally generating a new object with Ldap Login instead of username, and passing through the password. It is not possible to pass in several fields to this class, this is why replacements with more than one field, like `{firstname} {lastname}`, cannot be simply done here.
