### ISSUE TITLE
Changing filetypes in folders of active projects leads to exception when opening process

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#4833]
After changing the filetype of folders used for thumbnails or media views, opening existing processes of that project - that contain thumbnails/media views in the _previous_ format - in the metadata editor leads to an exception (caused by a non-matching regex):

![Bildschirmfoto 2021-11-23 um 14 13 46](https://user-images.githubusercontent.com/19183925/143030482-a056b15c-8f2d-4604-8d29-3e239304853f.png)

**Possible solutions:**
- either deactivate editing folders (or at least filetypes) for existing projects
- convert all images of all process of the selected project from the previous to the new fileformat

**Comment by matthias-ronge** [comment]
Changing the pictures is unacceptable in my opinion. First, there could cause data loss by conversion, and there may not be a backup. Second, it can cause a load problem (maybe that's a very large number of images).

The solution to forbid change for projects with processes seems right to me.

Changing the pictures is unacceptable in my opinion. First, there could be data loss due to conversion and there may not be a backup. Second, it can cause a load problem (maybe that's a very large number of images).

The solution to forbid change for projects with processes seems right to me.

_A subsequent change requires careful consideration, converting the images (this can require a lot of computing power, and backup for a lot of new data can be necessary. It is not trivial.) Then change the METS files and change the project settings. Anyone who really wants to do that should be aware and have to modify the database and have to perform reindexing._ Maybe we can support this administratively in the future, but that would be a new feature and must be implemented separately.
