### ISSUE TITLE
Rel 3.4 - changes in kitodo_config.properties

### ISSUE THREAD

**Issue by stefanCCS** [kitodo/kitodo-production#4843]
I could find changes in kitodo_config.properties in this Release 3.4 in comparison to Release 3.3.1.
The additional parameters are described in new kitodo_config.properties file and I could understand it
(but anyway, it would be good to put in release notes in the future a list with new/changed parameters).
My question in this issue here is, that I could identify, that the following parameters are NOT anymore in the kitodo_config.properties:
```
- language.force-default
- language.default
```
Are these parameters are not available anymore (function not given anymore)?

--> Please clarify.

**Comment by markusweigelt** [comment]
@stefanCCS Yes this parameters are not longer available since we solved #4676.

- language.force-default -> Parameter was not used
- language.default -> removed cause default application language is now configured at a single point in faces_config.xml - if faces context is not available we use language if available of browser, cookie, spring or default of system locale

**Comment by stefanCCS** [comment]
Ok, understood - many thanks.
