### ISSUE TITLE
Prevent the assignment of metadata to pages in the combined structure tree

### ISSUE THREAD

**Issue by BartChris** [kitodo/kitodo-production#4921]
It seems to be possible to assign every metadata key defined in the ruleset to single pages in the document using the combined structure tree. 

![grafik](https://user-images.githubusercontent.com/7516499/150522199-2f2d583a-d880-4d6f-a608-1a4a0511388b.png)

When a page is selected on the left side, a user can select all metadata elements defined in the ruleset and even assign values to them. It is therefor possible to assign a language to a page for example:

![grafik](https://user-images.githubusercontent.com/7516499/150522474-d06fd579-b9ae-4efe-9a80-1d904e57acc1.png)

This is a) not prevented by the ruleset validation and b) serialised into the meta.xml. In conseqeunce for a page with assoicated metadata an own dmdSec is generated which is referenced by the page in the physical structure. 

I am wondering
a) is this even allowed by the DFG METS/MODS-Anwendungsprofil?
b) What is the use case for assigning metadata to single pages?
c) can it be prevented?
d) Is this a bug or a configuration error on our side?

**Comment by matthias-ronge** [comment]
This is valid METS. You may want to assign metadata to pages, i.e. MIX metadata. Yes, you need to define special metadata keys to do so and create a mapping that exports them to MIX, not MODS, in your XSLT, but it is intentional.

Pages are of the internal type `division="page"`. So you can control the available metadata with the full power of the ruleset, by defining a `<restriction division="page">`.

**Comment by BartChris** [comment]
Thank you very much for the information and the fix. It works for me. This should probably be documented in the already very useful wiki page: https://github.com/kitodo/kitodo-production/wiki/Regelsatz-3.x
