### ISSUE TITLE
Remove time limit to start new indexing threads

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#4947]
`IndexingService` is running a main thread **IndexAllThread** which checks once in a second if there is a running indexing worker thread, and if not, it starts the next one. (This is the thread that brings the messages _Cannot start 'FOO' indexing while a different indexing process running: 'BAR'_ in the log file.) This loop runs for configurable `elasticsearch.indexLimit` iterations (defaults to 5000, which is 1 hour 23 minutes) and then ends.

IMHO, this thread shouldn’t ever end, unless it has completed its job. This behaviour is not understandable to users and should be removed.

**Goal:** Remove time limit.

**Comment by thomaslow** [comment]
Same as #3999. This was fixed by https://github.com/kitodo/kitodo-production/pull/5367. All indexing related threads are created when the user triggers the indexing process. The `IndexAllThread` (now `IndexManagmentThread`) still manages the sequential indexing of every type of object (process, task, etc.), but there is no time limit on that any more.

**Comment by andre-hohmann** [comment]
@thomaslow : Thanks a lot for your hint. That helps us to clean up the issues. 

@matthias-ronge : Can this issue be closed?

**Comment by matthias-ronge** [comment]
That’s the solution
