### ISSUE TITLE
Metadata Editor: Save state of open/closed comments or pagination window

### ISSUE THREAD

**Issue by m-kotzyba** [kitodo/kitodo-production#4978]
Similar to the state of "Structured view" or "Detail view", what is saved in the background and used each time if the Metadata editor is (re-)opened, it would be helpful to save also the state of open/closed comments or pagination window.

Alternatively, the option to set a default option on open/closed comments or pagination window in the User data & settings would solve this issue.

**Comment by solth** [comment]
> Similar to the state of "Structured view" or "Detail view", what is saved in the background and used each time if the Metadata editor is (re-)opened

This is actually an unintentional side effect of the Metadata Editor bean currently still being session scoped instead of view scoped (see #4868). This stems from the history of the software, which was created during JSF 1 ages, when view scope did not exist, yet, and will not be true anymore once the linked issue is fixed (which is also scheduled for the immediate future).

Therefor I would opt for your second solution to explicitely add a setting to control the default states of the pagination and comments panels to the user settings, if you agree. 

In order not to lose the "feature" you described above, I can also add a setting for the default view of the gallery, since otherwise this will not be saved for a session anymore once the editor is view scoped (as described above).

**Comment by m-kotzyba** [comment]
@solth Thank you for the detailed explanation. 

Yes, we agree with the second solution having default options for pagination, comments (and maybe even metadata & structure data) in the user settings.

My colleague made an image how she (sometimes) would like to have the arrangement:
 
![favo](https://user-images.githubusercontent.com/85474095/201024475-590e1c89-d3ff-4efa-b96d-eadec30d9ded.PNG)

Furthermore, yes, a default option for the gallery view would be helpful and consistent.
