### ISSUE TITLE
Extended Search: option to ignore upper and lower case 

### ISSUE THREAD

**Issue by m-kotzyba** [kitodo/kitodo-production#4980]
It would be helpful to select whether upper and lower case in the filter query strings are considered or not.

**Comment by matthias-ronge** [comment]
Here we probably have to take into account that this setting has to be made before indexing, and requires re-indexing everything if it is changed. Then this topic is not “easy” to deal with.

My expectation of a search engine is actually that case is not distinguished. Can you give me an example of a use case when distinguishing case in search is needed?

**Comment by matthias-ronge** [comment]
My question was meant the other way round: Do you have a case where you want, that **searching for „schweiz“*does not return** „Schweiz-Wochenschrift-Pharmacie-10-1872“ and „Schweitzer-Harz-Literatur-1“, **but searching for „Schweiz“ does?**

What I read from your post, you want case to be ignored, which is what I also think should be the default.

**Comment by m-kotzyba** [comment]
You are right, I misunderstood the question. Than my Answer is:

No, I can not give you an example where distinguishing the case in search is needed because we always try to make the process titles unique independent of the case.

**Comment by matthias-ronge** [comment]
**Goal:** search should be case-insensitive

**Comment by thomaslow** [comment]
There seems to be no easy way in ElasticSearch to make case-sensitivity optional at query time. They tried to implement this feature, see https://github.com/elastic/elasticsearch/issues/61162, but didn't go through with it. Theoretically, we could index each property (e.g. the process title) both in a lower-case variant and the original cased variant.

Since you agreed that this is not important, I modified the indexing to apply a lower-case filter to a few relevant properties, see pull request #5363.
