### ISSUE TITLE
Button to show superordinate process in process list

### ISSUE THREAD

**Issue by m-kotzyba** [kitodo/kitodo-production#4982]
In the process list, displaying further information of a superordinate process (via the arrow down button) allow to show all subordinate processes in a (new, filtered) process list (see image 1 and 2)

image 1:
![1](https://user-images.githubusercontent.com/85474095/153397209-f51648c3-0546-4e68-bb77-46f9e75b77d4.PNG)

image 2:
![2](https://user-images.githubusercontent.com/85474095/153398030-6bf14a50-5748-4b29-920f-856f23f2d993.PNG)

However, to show (all) superordinate processes of a subordinate process in a (new, filtered) process list is not possible with one click. The available options to open the “Edit”-Options or the Metadata Editor of a process’s superordinate processes (cf. image 2) is sometimes not sufficient, e.g. if a docket or METS file have to be generated. Instead the user has to filter “id:<Id-of-superordinate processes>” (cf. image 3) but even the ID is not directly available (cf. image 2).
 
image 3:
![3](https://user-images.githubusercontent.com/85474095/153397805-913b1005-1bac-4d33-a4bc-be6faa215abd.PNG)

**Comment by matthias-ronge** [comment]
_Background:_ The search for subordinations was initially the auxiliary solution, since there can be many (a newspaper with four issues, published six days a week has 1,250 subordinations in one year process). Actually, it would have been more integral to show them all there without search.

_Question:_ Do you want

1. **all parent processes** to be displayed (including the parent of the parent, and its parent, etc.), or
2. when the parent is displayed, **all action buttons** of the parent to be displayed (such as METS export), or
3. do you want to be able to **search for the parent by ID** directly with one click?

Or do you want several of these options?

**Comment by m-kotzyba** [comment]
For us, at first, option 3 would do the work because we want to quickly see the subordinates.

However, option 2 would be also great for us and probably also for others.

**Comment by matthias-ronge** [comment]
In this ticket, we should work on option 3. If you also like the other, please create a separate issue for it.
