### ISSUE TITLE
Performance improvement - Bundle

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#5017]
In Kitodo.Production 3.x several processes and functions are slow. This refers the display of lists (processes, users ...), opening and working in the metadata editor or the creation of newspaper processes. For the daily work, slow performance is very annoying and time consuming. The goal is to improve the user experience by solving the performance problems. 

The **cost estimation** is expected to be: **high**

High costs are expected, because the analysis and the identification of the causes in each case will take probably a lot of time. It must be assumed, that some problems occur only in systems with several hundred thousands of processes. 
Maybe some issues are solved by the hibernate search. This should be examined as soon as the hibernate search is implemented. 

_In the following the suggested Issues are listed_:

- #3533
- #4195
- #4196
- #4220
- #4221
- #4378
- #4782
- #4783
- #4760 
- #4928
- #4950
- #5012

**Comment by M3ssman** [comment]
@matthias-ronge What exactly do you mean with `search engine` ? The ELK-stuff?

**Comment by matthias-ronge** [comment]
Yes, I mean the ElasticSearch

**Comment by M3ssman** [comment]
I do really appreciate your position on this topic. It has been argued Elastic is there to have virtually all metadata indexed ... fancy at first sign, but actually, I've never missed this back in kitodo2.

Further, I agree that a more sophisticated usage of the underlying database system with proper indexing and so forth, as you already mentioned, should do the same job way easier. 

Another point versus Elastic: it increases the installation and support complexity a good deal (not to mention potential license and security issues).

Regarding the XML-Processing: Is this serious? If so, I'd be really interested to get to know why a fast-processing Component has been skipped during project evolution.

**Comment by matthias-ronge** [comment]
For XSLT processing: The main point for using JAXB is that it technically prohibits building wrong METS files, because it cannot handle unknown elements or attributes. (It is even so strict that we found the METS profile used in Germany up to that point contained a wrong referencing by ID.) This made develompent much safer, because a lot of new developers came into the project at that time, and we had really more significant performance issues at that time, so that these milli-second differences have not been taken too serious.

This is nothing bad, since we use an agile software development approach, which means that decisions can always be revised and re-decided otherways, if it seems to become necessary.

Why this could be revised: Over the time, there have come quite a lot of places through the application where it needs to look into the XML files (features that weren’t there at time of that decision either) so I can still think of using the other code may bring performance improvements. However, it is most relevant when many METS files have to be read together, and there are three places I think to know, without checking: during indexing, during newspaper migration, and when opening a year process of a newspaper. Maybe there are other good solutions as well, as storing more data in the search index.

**Comment by andre-hohmann** [comment]
As the main issues (performance regarding newspaper-processes, metadata editor, process lists) are solved, i close this issue. 

If other issues with regard to performance problems should be solved, it would be better to describe them separately.
