### ISSUE TITLE
translate user interface and user instructions into English and Spanish

### ISSUE THREAD

**Issue by kselmi** [kitodo/kitodo-production#5033]
As more and more potential users from English- and Spanish-speaking countries are getting interested in Kitodo, some of them already having started testing or using Kitodo.Production, it would be useful to translate the user interface into both languages.
An English translation of the user interface already exists, except for some details which deserve to be supplemented, such as the user instructions (= short introductory texts in the "help" menu).
As to Spanish, the entire user interface and user instructions would have to be translated.
(effort: low = 2 pt.)

**Comment by matthias-ronge** [comment]
I think you underestimate the effort. Even our German and English translation is not consistent everywhere (see #3500, #4139, #4174).

A translator would have to be found who is familiar with Spanish library jargon in order to translate meaningfully here. First, a suitable wording would have to be found. What is the equivalent term for workflow, process, properties, docket, ruleset, division, metadata key, metadata entry? Also, our _properties files_ don't translate easily because they provide very little context. Many of the meanings only become clear when you put the German and English versions and the technical key side by side. Some things may be completely incomprehensible to the outsider. This requires insider knowledge or a feedback loop to an expert.
