### ISSUE TITLE
Function "Select all rows" is not applied to KitodoScripts

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#5267]
**Describe the bug**
If a list of results with several pages is shown in "processes" and all processes are selected, the following occurs:
- The KitodoScpripts are only applied to the processes of the result page, which is shown to the user. 

**To Reproduce**

1. Search enough processes to generate a result list of several result pages.
2. Use function "select all rows".
3. Click on the icon for the next result page to see that all rows are selected.
4. Go back to the first result page
5. Click on "Actions"
6. Click on KitodoScript "addData" and use key and value according to the applied ruleset and execute the KitodoScript
7. Wait until the KitodoScript is finished. 
8. Open a process of the first result page and check, if the metadata has been added
9. Click on the icon for the second result page to see if all rows are selected
10. Open a process of the second result page and check, if the metadata has been added

**Expected behavior**
If all rows of a result list are selected, they all should be regarded, if a KitodoScript is applied.

**Screenshots**
function "select all rows"
![Trefferliste01](https://user-images.githubusercontent.com/14835770/187881135-9e673b45-5948-4ea4-a935-7f30db75b175.jpg)
function  "Actions"
![Trefferliste02](https://user-images.githubusercontent.com/14835770/187881156-d77f0a44-c053-40cd-8f55-8c812c690b17.jpg)

**Release**
Kitodo.Production version 3.4.4

**Desktop (please complete the following information):**
- OS: Windows 10
- Chrome 103.0.5060.134 (Offizieller Build) (64-Bit)

**Comment by matthias-ronge** [comment]
Even more: If you select all processes on all pages, and there are 15 pages, the KitodoScript is executed 15 times for each process of page 1.

Correct behaviour should be: The script should be executed once for each process of each page.

**Comment by andre-hohmann** [comment]
Thanks a lot for your addition. I would not close the issue as duplicate, because in the other issue, only the generation of images is described. 
It is important to me to point out, that other functions are affected from this behavior, too.

**Comment by BartChris** [comment]
I just looked into it and the problem does not appear if i select all processes by hand, only if the functionality "Select all rows" is used. In this case the process list is already incorrect before the data is passed to the actual processing.

**Comment by andre-hohmann** [comment]
@BartChris : Thanks a lot for the contribution. I hope that this supports the solution of the issue. 

You are right, regarding the possible relocation of the function into the batch interface or another interface. 
That would be more appropriate in [Discussion](https://github.com/kitodo/kitodo-production/discussions) - only after all aspects are analyzed and discussed, an issue with a precise demand/proposal should be created. 
I guess, that it will be a major feature/improvement. 

For me, it is important that the current implementation works correctly - although it might not be the best implementation.

**Comment by BartChris** [comment]
It seems as if the issue can be fixed, when the "select all" functionality is not delegated to the Primefaces mechanism but is implemented by hand.

I added the following method to ProcessForm.java (ProcessBaseListView.java)

```java
 public void selectAll() throws DataException {
          ProcessService processService = ServiceManager.getProcessService();
          this.selectedProcessesOrProcessDTOs =    processService.findByQuery(processService.getQueryForFilter(this.isShowClosedProcesses(),
                isShowInactiveProjects(),getFilter()), false);
    }
```
and added button to call that method. This queries the search index with the current filter settings and sets the currently selected records to all elements in the result.

I have the impression that implementing that mechanism as a custom method is the only way to determine what data is actually selected, when the user chooses "Select all".
Another advantage is that the user can also unselect columns without losing the other selections. This also fixes the issue https://github.com/kitodo/kitodo-production/issues/5266.

**Comment by solth** [comment]
@BartChris thanks for this proposed fix. I wonder, though, if it is a viable solution to load _all_ elements in a real production system with millions of processes instead of just 13 like in your example. I think that is the main reason why the "Select all" button hasn't been implemented in this most straight-forward way until now. I guess we need to find a solution where the `selectedProcessesOrProcessDTOs` variable does not really have to hold all those processes at once but instead fake the selection and somehow apply the "lazy loading" principle here as well.

**Comment by BartChris** [comment]
@solth You are correct i suppose. Holding a lot of processes in memory is probably not a good idea and it would be probably be better if the triggering the button which e.g. just sets a variable `allProcessesSelected` to `true` and then those processes can be retrieved when the list of all processes is actually needed. -> when "getSelectedProcesses" is called. (This seems to be more or less the appoach of Primefaces, except that it does not seem to work with the native mechanism)

Doing it that way would probably also reintroduce the problem that after clicking only on  a single row, all other selections are lost. So that it is impossible to unselect processes even if they should not be included in the batch process.
