### ISSUE TITLE
Meta data editor: wrong validation result on wrong image count

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#5281]
**Describe the bug**
If you changed the amount of images on a correction workflow and use the validation button in the meta data editor you get no error message that there are not paginated images or previous paginated images are now missing. Validation tell you that everything is okay but this is not the case and the opposite to 2.x.

**To Reproduce**
1. Process a process like normal
2. Start a correction workflow in the meta data editor
3. Add / Remove some images outside of the meta data editor and close the correction workflow successful
4. Open the meta data editor for this process and click on the validation button

**Expected behavior**
Validation in meta data editor should even check that the amount of paginated images to the real amount of images inside the defined image directory like in 2.x and show error messages if there are images missing which are not paginated or paginated images which are missing or ...

**Release**
3.4.4-SNAPSHOT

**Comment by henning-gerhardt** [comment]
This issue is not related to #5282 but will increase the error rate for #5282 in a significant way!

**Comment by matthias-ronge** [comment]
These are two different cases to consider:

- If there are images that aren’t paginated, we don’t know if they just don’t have a page number to paginate them. So checking for this is a too strict restiction. Maybe it makes sense to define a property in the project settings, whether all images must be paginated for export

- If there are images removed, this is typically intentional and they should be removed once you open the metadata editor. Having access to the file system in a way that you are able to delete images comes with high responsibility, and the fact that the images were deleted typically counts higher than that they were used in the past for some reason. Without a versioning file system approach, we have no possibility to restore the missing images programmatically. However, it could possibly show a warning like “6 previously known media units have been deleted on the file system. They will be removed from the document structure. Do you want to continue?“ If you press cancel, the METS file will not be changed and you can fix the problem.

**Comment by henning-gerhardt** [comment]
* For your first scenario: even if they did not have a number you should get a warning / error message that shows you that there are not paginated pages and let the user decide to paginate them or use a no pagination label like in 2.x.
* For your second scenario: Kitodo.Production should not care about restoring any images or files which are deleted outside but Kitodo,Production must show the user that there are images missing and the user must decide what is to do. So your mentioned text out put must appear in this case.

**Comment by andre-hohmann** [comment]
Just to make sure, that we write about the same concept: 

@henning-gerhardt means with "pagination" the function "Read in pagination from images" (See: [Paginierung einlesen](https://github.com/kitodo/kitodo-production/wiki/Paginieren#paginierung-einlesen)). This is not the correct label, because the pagination is not conducted, but the creation of the necessary elements in the METS-file (`<mets:fileSec>`, `<mets:structLink>` , ...) is initiated. 

In 2.x this function is used in the SLUB Dresden after deletion/adding of files, so that the METS-file contains the correct amount of image files and the correct internal links. 
In the SLUB Dresden, image files are deleted/added on the file system to enable the creation of md5-files, ...

I just recognized, that the button "Read in pagination from images" exists in 3.x, but without functionality. Thus it is not possible to adjust the METS-file according to the changes of images files. If image files are deleted, empty frames are shown in the metadata editor
It seems as if a new process needs to be created after changes of the amount of image files.

**Comment by solth** [comment]
> If image files are deleted, empty frames are shown in the metadata editor
> It seems as if a new process needs to be created after changes of the amount of image files.

@andre-hohmann would it be an option for you to add/delete images using the context menu in the metadata editor instead of the file system?

**Comment by henning-gerhardt** [comment]
Adding / Deleting / Exchaning images files in SLUB is more complicated and can not be done inside the meta data editor. Every image file need a valid checksum, must be valid against our long term preservation rules, must follow a strict file name ruling and the creation of the derivatives for the meta data editor is done outside of Kitodo.Production.

**Comment by andre-hohmann** [comment]
@solth : Unfortunately not. In the SLUB Dresden we deliberately avoid the adding/deleting of image files in the metadata editor, because we have very strict specifications from the SLUBArchiv. 
@henning-gerhardt was quicker in writing then me, but i agree with him.

**Comment by andre-hohmann** [comment]
In addition: Maybe in other institutions, the image files are added/deleted also in the file system.
