### ISSUE TITLE
Validation mis-enforces required fields in empty always-showing metadata group

### ISSUE THREAD

**Issue by matthias-ronge** [kitodo/kitodo-production#5297]
**Describe the bug**
If you have an `alwaysShowing` nested metadata key, with sub-keys that are declared `minOccurs` > 0, in process creation, the validation complains about these fields to be empty and refuses creating the process.

**Expected behavior**
If the `alwaysShowing` metadata group is all empty, the validation should not complain about these fields to be filled. If there is any data in any sub-field of the metadata group, then the validation should require these fields to be filled.

**Comment by BartChris** [comment]
related: https://github.com/kitodo/kitodo-production/issues/5437

**Comment by BartChris** [comment]
Do you want this only for metadata groups which are set to `alwaysShowing` or for all non-required metadata groups and is this only about process creation? I would like to prevent people from adding e.g. a `person` (which is not required) but without specifying any data (for example a name), so that the export would end up with a METS file with person elements without any content. Would that be covered by the intended implementation?

**Comment by matthias-ronge** [comment]
That shouldn’t be saved anyway. The problem is, that you cannot save during process creation if it is empty.
