### ISSUE TITLE
Dialog for adding additional metadata in Massimport form does not contain any values

### ISSUE THREAD

**Issue by BartChris** [kitodo/kitodo-production#5345]
**Describe the bug**

The dialog for adding additional metada during massimport does not contain any values in my setup although there are a lot of metadata keys defined.. 

**Screenshots**
![grafik](https://user-images.githubusercontent.com/7516499/188180837-c58592ff-6594-4a71-9aa4-f1afef6b144c.png)

**To Reproduce**
1. Go to massimport form
2. Upload a csv file 
3. Try to add additional metadata values

The current behaviour in the mass import Service seems wrong to me

https://github.com/kitodo/kitodo-production/blob/712ba310a31cdbd17a5551be70a03c25e564490b/Kitodo/src/main/java/org/kitodo/production/services/data/MassImportService.java#L151-L154

It seems (and my tests confirm that) as if the algorithm works the following: If the currently inspected division does not contain a value of the collected list of all metadata elements from different division types: delete those values from the collected list of metadata elements. That means if first a monograph division is inspected and then a periodical division, the collected list of metadata does contain almost no elements because the two division types do not share many fields. In my case the process ends with zero metadata elements collected.

It would probably be more correct to collect unique elements from all divisions, for example like that:

```java
List<String> commonMetadataIds = commonMetadata.stream().map(metadataelem ->
                   metadataelem .getId()).collect(Collectors.toList());
metadataView.removeIf(item -> commonMetadataIds.contains(item.getId()));
commonMetadata.addAll(metadataView);
```  
This works for me, it does however not collect all metadata, because some rules are applied which restrict the selectable metadata. 

**Expected behavior**
The dialog should list all avaible metadata values. 

**Release**
3.4.4 SNAPSHOT

**Comment by solth** [comment]
This is intended behaviour because the metadata is added to _all_ imported processes, which can have different document types that in turn allow different sets of metadata according to the ruleset. Thus, only metadata that is allowed in all documents is offerend in the popup dialog.

In other words, the list in the popup contains the **intersection** of allowed metadata element from all document types in the ruleset, not the **union** of those metadata elements. Otherwise, processes would be created during mass import where metadata validation automatically fails. 

This corresponds to the standard import, where only metadata can be added that is allowed according to the rules in the configured ruleset. 

You can add arbitrary metadata to individual records during mass import by clicking the "+" symbol in the header and then only add values to those records where you need that specific metadata.

**Comment by BartChris** [comment]
Thanks, this makes sense, when i think about it.

**Comment by BartChris** [comment]
What i do not get right now: Click "+" always opens the dialog with the allowed metadata elements. 

![grafik](https://user-images.githubusercontent.com/7516499/188204157-0559bd09-c533-46a3-8323-76777b81689b.png)

I cannot add custom headers there. Am i overlooking something?

**Comment by solth** [comment]
@BartChris no, you are right, my description about how to add arbitrary metadata was not correct. The "+" symbol always opens the "Add Metadata" dialog where the available metadata keys are restricted in the way described above. The only way to add arbitrary metadata is by uploading a CSV file where the additional columns can contain any string in the first line that is then used as the metadata key during mass import!

**Comment by BartChris** [comment]
Allright, thank you - since it is no a bug, but a feature, will close the issue ;)
