### ISSUE TITLE
Placeholders for script arguments

### ISSUE THREAD

**Issue by mnscholz** [kitodo/kitodo-production#5425]
Is there any documentation on which placeholders for script command arguments exist in Kitodo 3 and what they expand to?

#3718 discusses which placeholders should still be supported by Kitodo 3, but it leaves me a bit puzzled about what holds now. Looking at the Regex that searches for these placeholders in [VariableReplacer.java#L70)](https://github.com/kitodo/kitodo-production/blob/7f3609cbc485fb7cc12a2d12c2be6d948b7b0c40/Kitodo/src/main/java/org/kitodo/production/helper/VariableReplacer.java#L70), it seems like you can access more specific/any process metadata (using `meta.*`). However, I'm not sure about the right syntax and what are the differences between `meta`, `process`, `product`, etc. 

Any help appreciated!

**Comment by matthias-ronge** [comment]
I do not know of any documentation of these.

The variables `(prefs)`, `(processid)`, `(processtitle)`, `(projectid)`, `(stepid)`, and `(stepname)` (**without** leading `$` sign) reference to technical properties. For example, `(processid)` can be passed to a script task in a workflow, to tell the script which process data folder to use. `(stepid)` can be passed to a script task, so that the script can use Active MQ close step interface to finish the step after a background job has completed.

Some more technical property variables did exist in Production 2, and for completeness, they [have been moved to `kitodo_config.properties`](https://github.com/kitodo/kitodo-production/blob/master/Kitodo/src/main/resources/kitodo_config.properties#L106-L129).

Further more, in Production 3, you can use `$(meta.‹key›)` to refer to metadata values, for example: `$(meta.TitleDocMain)`  
Long story: The variables that look like `$(aa.cc)` and `$(aa.bb.cc)` (**with** leading `$` sign) reference values of metadata entries.  
In Production 2, metadata entries could be in the _meta.xml_ file (aa = `meta`), but it could also be in three database tables of the process called process properties (aa = `process`, _Germ._ Vorgangseigenschaften), template properties (aa = `template`, _Germ._ Vorlageneigenschaften), and workpiece properties (aa = `product`, _Germ._ Werkstückeigenschaften). Those tables are subject to removal in Production 3, but removal isn’t yet complete (see issue #4317).

`$(aa.cc)` will look for the metadata value in the first child division below the document’s root division, and if it doesn’t find it there, then in the root division of the logical structure (the doc type).

```
📂 Anthology
│  📃 TitleDocMain: Current research on magnetism
│  📃 singleDigCollection: Science publications
│  📃 singleDigCollection: New digitizations programme
├── 📂 Article
│      📃 TitleDocMain: Magnetism rules
│      📃 Person: Smith, John
│      📃 Person: Miller, Michael
```

`$(meta.TitleDocMain)` → Magnetism rules
`$(meta.singleDigCollection)` → Science publications
`$(meta.Person)` → Smith, John

Only the first matching entry will be returned, so there is no way to obtain “singleDigCollection: New digitizations programme” or “Person: Miller, Michael”.

`topstruct` and `firstchild` will reference to one specific of these two divisions:

`$(meta.topstruct.TitleDocMain)` → Current research on magnetism
`$(meta.topstruct.singleDigCollection)` → Science publications
`$(meta.topstruct.Person)` → _(empty)_
`$(meta.firstchild.TitleDocMain)` → Magnetism rules
`$(meta.firstchild.singleDigCollection)` → _(empty)_
`$(meta.firstchild.Person)` → Smith, John

Note, that there is no way to address other divisions, so no _secondchild_, _firstchildfirstchild_, etc. ([ReadMetadataSelector](https://github.com/kitodo/kitodo-production/issues/3368#issuecomment-781961426)s, as specified as part of reimplementation of CopyData expressions (not yet implemented) would allow for such.)

**Comment by mnscholz** [comment]
Thanks @matthias-ronge , that helps a lot!

I have two follow-up questions:
1) Why is there a distinction in the use of the `$` sign? Is it for legacy reasons? If so, will it be subject to change?
2) How can I access metadata of periodicals? I.e. when I run a script for a certain issue, how can i access the TitleDocMain of the top-level process? And which fields provide me the issue/date information (the information that is typically added to to process title)?

**Comment by matthias-ronge** [comment]
1. The behaviour of the `$` sign was inherited this way from old code. For backward compatibility, I didn’t change it.
2. There are no other than the variables I listed above. Since in Production 3, the periodical information is in the hierarchically superior process, there is no way to access it here. If you have the issue/date information in a metadata field, then you can access it, else you can’t.
