### ISSUE TITLE
Collapsed/expanded structure tree nodes not properly updated

### ISSUE THREAD

**Issue by solth** [kitodo/kitodo-production#5540]
**Describe the bug**
As discovered by @m-kotzyba during tests of #5520 the tree node icons in the metadata editors structure tree are not properly updated when closing/expanding individual nodes. This problem does occur in the master branch as well.

**To Reproduce**
1. Open a process in the metadata editor
2. Collapse an open structure element in the structure tree 

**Expected behavior**
The icons should change depending on whether a structure tree node is collapsed or expanded.

**Screenshots**
https://user-images.githubusercontent.com/19183925/218791566-81f6506a-b824-40fa-8403-9f62f7ff63c8.mp4

**Release**
3.6.0-SNAPSHOT

**Comment by IkramMaalej** [comment]
This bug only occurs when the last node in the  structure tree is a page and not a structural element. This means either there is one or more unstructured media, or the last structural element node in the tree has a page as its last child.

**Comment by thomaslow** [comment]
I had a quick look at this problem before. The issue is that the `<p:treeNode ... />` component in `Kitodo/src/main/webapp/WEB-INF/templates/includes/metadataEditor/logicalStructure.xhtml`  doesn't use the `type` attribute to distinguish folder-nodes  from documents-nodes as described in the Primefaces 8 [documentation](https://www.primefaces.org/showcase-v8/ui/data/tree/icon.xhtml). Because of the missing type attribute, PrimeFaces [doesn't know](https://github.com/primefaces/primefaces/blob/8.0/src/main/resources/META-INF/resources/primefaces/tree/tree.vertical.js#L359-L368) what icons to use when a folder is expanded or collapsed.

Unfortunately, it's not sufficient to add the type attribute in JSF. The treeNode backend bean instances need that type attribute as well, otherwise there are additional errors in PrimeFaces.
