### ISSUE TITLE
File references are gone on editing meta data entries of finished process

### ISSUE THREAD

**Issue by henning-gerhardt** [kitodo/kitodo-production#5579]
**Describe the bug**

Solving the issue #5285 changed the update of file references. A lot of use cases were discussed but this one was missed:

* Opening completed processes (all tasks green) without files (media files (LOCAL) and derivatives) in the metadata editor leads to the loss of the file references.
  * If either the media files inside the source directory (LOCAL) or the media files in the derivative directories are available then the file references are kept.
* There is no message, that the references are removed
* We discovered this use case because of [this comment](https://github.com/kitodo/kitodo-production/issues/4999#issuecomment-1447743880).

The use case is important for the SLUB Dresden due to the following reasons: 

1. The media files (LOCAL) are archived, when a process is completed. 
2. The derivatives are deleted, when a process is completed. 
3. In completed processes, metadata is corrected or completed, or structural data is supplemented. 

Thus, it is now impossible to correct metadata of completed processes and save the corrections without losing the references. 

**To Reproduce**

1. Open a process in meta data editor which contains file references but no the media files (original and derivatives)
2. Save the process in meta data editor
3. References to files are gone

**Expected behavior**

If processes with references but without any media files are modified in the metadata editor, the references should not be removed. 

At least, there should be a message that includes an explicit request for the user to delete the references. If this is not confirmed, the references remain. This message must be worded very clearly to avoid accidental wrong selection. 

**Release**

master branch from 2023-03-01 commit 414b1b4

**Comment by BartChris** [comment]
> At least, there should be a message that includes an explicit request for the user to delete the references. If this is not confirmed, the references remain. This message must be worded very clearly to avoid accidental wrong selection.

I also think that this is absolutely essential. I want to add here that there might also be the scenario, that only the large Tiff files are moved to another system and the derivatives stay where they are. It is OK if Kitodo would not be fully functional at this point but the System should never automatically without any warning remove references to the originals.  I have not checked this: Was the concept of deletion of references originally not bound to the user expliciteley using a button? (https://github.com/kitodo/kitodo-production/issues/5285)

**Comment by andre-hohmann** [comment]
@BartChris : 
You are right, as long as derivatives or the original data are available, the references are not removed. 
You are also right, that the reference update is realized in Kitodo.Production 2 manually with the function "[Paginierung anhand der Images einlesen](https://github.com/kitodo/kitodo-production/wiki/Metadateneditor---Allgemeines#mittlerer-hauptbereich-f%C3%BCr-das-erstellenbearbeiten-der-meta--und-strukturdaten-mit-den-arbeitsschritten)". However, this is sometimes forgotten in the SLUB Dresden and leads to inconsistent references that were recognized in Kitodo.Production 2 during the export. The processes were then corrected manually. 
Since in Kitodo.Production 3, the references are not checked during the export, we wanted to have the check of the references carried out automatically when the metadata editor is opened. From our point of view, this increases the probability that the references are updated after corrections. 

Unfortunately, I just did not consider the cases, when processes are completed and there are no files available to check - although, the function “Paginierung anhand der Images einlesen” leads in Kitodo.Production 2 to the loss of pagination information, too, when the files are not available anymore. 
 
Oddly enough, different behavior did occur: 

- In one of our systems (in which i have tested the results of #5285), the references of migrated processes which do not contain image files, are not removed. 
- For newly created processes in which image files were first added and then removed, the references are removed. 

Maybe after the next migration, the references of migrated processes are removed, too. 

We are examining the possible solutions.

**Comment by andre-hohmann** [comment]
After some examination, i can imagine the following options to solve the problem: 

1. If no master or derivative files are present, no actions are performed: The references remain and no warning/notice is displayed. This should correspond to the behavior described in https://github.com/kitodo/kitodo-production/issues/4999#issuecomment-1447743880
_Consequence_: It is impossible to delete all references. 
2. If no masters or derivative files are present, the references remain and a warning/notice is displayed and indicates that deviations exist to the current references, but the references are not adjusted accordingly. 
_Consequence_: It is impossible to delete all references. 
3. If no masters or derivative files are present, a warning/notice is displayed and it can be confirmed or rejected whether the references should be adjusted accordingly.
_Consequence_: It is possible to delete all references. 

Option 1 seems to be the less complicated one regarding realization and i would be fine with it. As there might be different demands or even better options, i want to ask, if this solution would be applicable in general. 

@BartChris , @matthias-ronge : It seems as if you have thought about it and i would be interested in your opinion regarding a solution.

**Comment by BartChris** [comment]
@andre-hohmann Thanks a lot for your thoughts on that,
What i have not understood/checked fully: Does the system already, without any action by the user, delete file references? 
https://github.com/kitodo/kitodo-production/issues/4999 is not implemented yet, but if understand the issue correctly, automatic deletion of file references is already happing in the current Master.

But since https://github.com/kitodo/kitodo-production/issues/4999 is planned in general, stale file references will be deleted automatically in the future. I am OK with that.

Regarding your question what to do in case of no files present at all (SLUB case after long term archival), i would suggest that
a) a warning message is displayed that  "indicates that deviations exist to the current references, but the references are not adjusted accordingly", but maybe also
b) allow the deletion of those references by explicitly using the "Update file references" button (again with a confirmation dialog). Since the deletion of all references is dangerous this should only be possible explicitly.

**Comment by henning-gerhardt** [comment]
> What i have not understood/checked fully: Does the system already, without any action by the user, delete file references?

If you open such a process without any image / derivative files in the meta data editor and click on save then already the references are deleted in the new meta data file of the process.

**Comment by matthias-ronge** [comment]
I think, when you want to delete both all images, and all references, why don’t you just delete the process then? So it wouldn’t miss something if it isn’t possible to delete all references. Or do you know a case where deletion of all references is needed, but deleting the process isn’t an option?

**Comment by andre-hohmann** [comment]
> I think, when you want to delete both all images, and all references, why don’t you just delete the process then? So it wouldn’t miss something if it isn’t possible to delete all references. Or do you know a case where deletion of all references is needed, but deleting the process isn’t an option?

I absolutely agree with you, but I want to make sure that this is common sense. In the past few years i was more then once surprised about the different demands or edge cases. 
I want to avoid that discussions start after improvements have been implemented.

**Comment by BartChris** [comment]
I am fine with this as well.

**Comment by andre-hohmann** [comment]
As the main aim of the SLUB is to avoid the complete removal of file references of completed (green) processes, we support the following solution 
> With the current implementation of this pr, the references are not remove and only a warning message shows what happend.

- See: #5598

Only a message without interaction is shown - this should correspond to proposal no. 2 in https://github.com/kitodo/kitodo-production/issues/5579#issuecomment-1460308477. 
If an interaction (confirmation/rejection) is needed, the current solution can be adjusted by a another development/PR.
