### ISSUE TITLE
It should be possible to edit/delete comments

### ISSUE THREAD

**Issue by pontus-osterdahl** [kitodo/kitodo-production#5702]
**Is your feature request related to a problem? Please describe.**
To the best of my knowledge, it is currently not possible to delete or edit the content of existing "non-correction" comments. 

**Describe the solution you'd like**
It should be possible to edit and delete "non-correction" existing "non-correction" comments. 

**Additional context**
Since the effects of "correction comments" on workflow etc are more complex, the possibility of editing/deleting them should be handled separately.

**Comment by matthias-ronge** [comment]
I find it good; but if someone has already replied to the comment, you shouldn't be able to edit it, or operators who read the thread later will get confused.

**Comment by pontus-osterdahl** [comment]
That's a good point, perhaps only the most recent comment should be editable?

**Comment by henning-gerhardt** [comment]
Should be there not at least some roles / rights for editing and / or deleting comments? Without them it is possible for every user to edit / delete the comments.

**Comment by pontus-osterdahl** [comment]
I agree. I would tend to allow at least the author of the comment to edit and delete it. We could also add further authorities (edit and delete comments on client and global level) to allow users to edit/delete any comments.

**Comment by BartChris** [comment]
> I find it good; but if someone has already replied to the comment, you shouldn't be able to edit it, or operators who read the thread later will get confused.

I just worked on an extended permission system for deleting comments. https://github.com/kitodo/kitodo-production/issues/6363

The rule to allow edits only on the last comment is quite problematic since comments not necessarily represent a "thread" but could just be different comments. And in that constellation i cannot delete an older comment because it is not the last comment, even if both comments are totally unrelated. The current behaviour encodes assumptions about a specific usage of the system, which are not necessarily true.

In addition to that: When the first comment is a "correction comment" it is impossible to delete older "normal" comments.

What should we do here? I would suggest, that at least the person with additional rights should be able to delete _every_ info comment. What do you think?
