### ISSUE TITLE
Add buttons to browse the files in the detail view of the metadata editor

### ISSUE THREAD

**Issue by andre-hohmann** [kitodo/kitodo-production#5930]
**Is your feature request related to a problem? Please describe.**
In Kitodo.Production 3 it is difficult to navigate in the detail view of the metadata editor - especially for users who are not used to apply short keys. 
This has been discussed in: 
- https://github.com/kitodo/kitodo-production/discussions/5881

**Describe the solution you'd like**
Two buttons should be created for the detail view to move forward and backward in the files. 
- For each klick on the "forward-button": the next file should be shown. 
- For each klick on the "backward-button": the file before should be shown.

**Comment by thomaslow** [comment]
In my opinion, the intuitive position for these buttons would be at the bottom of the detail view. However, this means, even more buttons are drawn on top of the actual image, possibly obstructing the user's view onto the image, which means the user needs to move the image around.

Usually, I do not like the idea of control elements that disappear depending on the mouse position because they would not be accessible for mobile or tablet users. Maybe in this particular case, it makes sense to hide these buttons when they are not needed (if the mouse cursor is outside of the detail view)? Here is a demonstration:

https://github.com/user-attachments/assets/2f49dab1-5294-485d-ab3c-380eca786881

What do you think?

**Comment by thomaslow** [comment]
@solth @andre-hohmann  What do you think?

**Comment by solth** [comment]
I think those disappearing buttons are appropriate. It's true that the metadata editor already has a lot of UI command components and buttons, but all of them serve some relevant purpose. 

Perhaps we can consolidate the current number of UI elements in the future and group some buttons into menus like you did for the structure tree in the past or for the data editor settings in #6245 but for the moment these two new, disappearing buttons are a good solution, IMHO.

**Comment by thomaslow** [comment]
I added fast-forward buttons that skip 20 images (which also is supported by keyboard shortcuts). See demo video in #6293.
