### ISSUE TITLE
Use annotated tags for future releases

### ISSUE THREAD

**Issue by stweil** [kitodo/kitodo-production#6037]
Please use annotated tags instead of lightweight tags for future releases of kitodo-production. Ideally the tags should also be signed with a key.

Citation from `man git-tag`:
"Annotated tags are meant for release while lightweight tags are meant for private or temporary object labels."

Meanwhile there are 13933 commits since the last annotated tag.

**Comment by solth** [comment]
@stweil Thank you for pointing this out. I have been using the GitHub feature to create new tags for new releases, but apparently this feature only uses lightweight tags instead of annotated tags (see https://github.com/orgs/community/discussions/4924)

I will try to create an annotated tag manually for the next version and then select it when drafting the release.

**Comment by solth** [comment]
@stweil I have used an annotated tag for the most recent release 3.6.3 (https://github.com/kitodo/kitodo-production/releases/tag/kitodo-production-3.6.3) so I will close this issue. Please feel free to re-open it if I missed something.
